package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * AcceptedSynonym generated by hbm2java
 */
@Entity
@Table(name = "accepted_synonym", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "synonym_id",
		"accepted_id" }))
public class AcceptedSynonym implements java.io.Serializable {

	private long id;
	private long version;
	private TaxonomyDefinition taxonomyDefinitionBySynonymId;
	private TaxonomyDefinition taxonomyDefinitionByAcceptedId;

	public AcceptedSynonym() {
	}

	public AcceptedSynonym(long id, TaxonomyDefinition taxonomyDefinitionBySynonymId,
			TaxonomyDefinition taxonomyDefinitionByAcceptedId) {
		this.id = id;
		this.taxonomyDefinitionBySynonymId = taxonomyDefinitionBySynonymId;
		this.taxonomyDefinitionByAcceptedId = taxonomyDefinitionByAcceptedId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "synonym_id", nullable = false)
	public TaxonomyDefinition getTaxonomyDefinitionBySynonymId() {
		return this.taxonomyDefinitionBySynonymId;
	}

	public void setTaxonomyDefinitionBySynonymId(TaxonomyDefinition taxonomyDefinitionBySynonymId) {
		this.taxonomyDefinitionBySynonymId = taxonomyDefinitionBySynonymId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accepted_id", nullable = false)
	public TaxonomyDefinition getTaxonomyDefinitionByAcceptedId() {
		return this.taxonomyDefinitionByAcceptedId;
	}

	public void setTaxonomyDefinitionByAcceptedId(TaxonomyDefinition taxonomyDefinitionByAcceptedId) {
		this.taxonomyDefinitionByAcceptedId = taxonomyDefinitionByAcceptedId;
	}

}
