package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AclClass generated by hbm2java
 */
@Entity
@Table(name = "acl_class", schema = "public")
public class AclClass implements java.io.Serializable {

	private long id;
	private String class_;
	private Set aclObjectIdentities = new HashSet(0);

	public AclClass() {
	}

	public AclClass(long id, String class_) {
		this.id = id;
		this.class_ = class_;
	}

	public AclClass(long id, String class_, Set aclObjectIdentities) {
		this.id = id;
		this.class_ = class_;
		this.aclObjectIdentities = aclObjectIdentities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "class", nullable = false)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclClass")
	public Set getAclObjectIdentities() {
		return this.aclObjectIdentities;
	}

	public void setAclObjectIdentities(Set aclObjectIdentities) {
		this.aclObjectIdentities = aclObjectIdentities;
	}

}
