package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclEntry generated by hbm2java
 */
@Entity
@Table(name = "acl_entry", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"acl_object_identity", "ace_order" }))
public class AclEntry implements java.io.Serializable {

	private long id;
	private AclSid aclSid;
	private AclObjectIdentity aclObjectIdentity;
	private int aceOrder;
	private boolean auditFailure;
	private boolean auditSuccess;
	private boolean granting;
	private int mask;

	public AclEntry() {
	}

	public AclEntry(long id, AclSid aclSid, AclObjectIdentity aclObjectIdentity, int aceOrder, boolean auditFailure,
			boolean auditSuccess, boolean granting, int mask) {
		this.id = id;
		this.aclSid = aclSid;
		this.aclObjectIdentity = aclObjectIdentity;
		this.aceOrder = aceOrder;
		this.auditFailure = auditFailure;
		this.auditSuccess = auditSuccess;
		this.granting = granting;
		this.mask = mask;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sid", nullable = false)
	public AclSid getAclSid() {
		return this.aclSid;
	}

	public void setAclSid(AclSid aclSid) {
		this.aclSid = aclSid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acl_object_identity", nullable = false)
	public AclObjectIdentity getAclObjectIdentity() {
		return this.aclObjectIdentity;
	}

	public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
		this.aclObjectIdentity = aclObjectIdentity;
	}

	@Column(name = "ace_order", nullable = false)
	public int getAceOrder() {
		return this.aceOrder;
	}

	public void setAceOrder(int aceOrder) {
		this.aceOrder = aceOrder;
	}

	@Column(name = "audit_failure", nullable = false)
	public boolean isAuditFailure() {
		return this.auditFailure;
	}

	public void setAuditFailure(boolean auditFailure) {
		this.auditFailure = auditFailure;
	}

	@Column(name = "audit_success", nullable = false)
	public boolean isAuditSuccess() {
		return this.auditSuccess;
	}

	public void setAuditSuccess(boolean auditSuccess) {
		this.auditSuccess = auditSuccess;
	}

	@Column(name = "granting", nullable = false)
	public boolean isGranting() {
		return this.granting;
	}

	public void setGranting(boolean granting) {
		this.granting = granting;
	}

	@Column(name = "mask", nullable = false)
	public int getMask() {
		return this.mask;
	}

	public void setMask(int mask) {
		this.mask = mask;
	}

}
