package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclObjectIdentity generated by hbm2java
 */
@Entity
@Table(name = "acl_object_identity", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"object_id_class", "object_id_identity" }))
public class AclObjectIdentity implements java.io.Serializable {

	private long id;
	private AclClass aclClass;
	private AclObjectIdentity aclObjectIdentity;
	private AclSid aclSid;
	private boolean entriesInheriting;
	private long objectIdIdentity;
	private Set aclObjectIdentities = new HashSet(0);
	private Set aclEntries = new HashSet(0);

	public AclObjectIdentity() {
	}

	public AclObjectIdentity(long id, AclClass aclClass, boolean entriesInheriting, long objectIdIdentity) {
		this.id = id;
		this.aclClass = aclClass;
		this.entriesInheriting = entriesInheriting;
		this.objectIdIdentity = objectIdIdentity;
	}

	public AclObjectIdentity(long id, AclClass aclClass, AclObjectIdentity aclObjectIdentity, AclSid aclSid,
			boolean entriesInheriting, long objectIdIdentity, Set aclObjectIdentities, Set aclEntries) {
		this.id = id;
		this.aclClass = aclClass;
		this.aclObjectIdentity = aclObjectIdentity;
		this.aclSid = aclSid;
		this.entriesInheriting = entriesInheriting;
		this.objectIdIdentity = objectIdIdentity;
		this.aclObjectIdentities = aclObjectIdentities;
		this.aclEntries = aclEntries;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "object_id_class", nullable = false)
	public AclClass getAclClass() {
		return this.aclClass;
	}

	public void setAclClass(AclClass aclClass) {
		this.aclClass = aclClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_object")
	public AclObjectIdentity getAclObjectIdentity() {
		return this.aclObjectIdentity;
	}

	public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
		this.aclObjectIdentity = aclObjectIdentity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_sid")
	public AclSid getAclSid() {
		return this.aclSid;
	}

	public void setAclSid(AclSid aclSid) {
		this.aclSid = aclSid;
	}

	@Column(name = "entries_inheriting", nullable = false)
	public boolean isEntriesInheriting() {
		return this.entriesInheriting;
	}

	public void setEntriesInheriting(boolean entriesInheriting) {
		this.entriesInheriting = entriesInheriting;
	}

	@Column(name = "object_id_identity", nullable = false)
	public long getObjectIdIdentity() {
		return this.objectIdIdentity;
	}

	public void setObjectIdIdentity(long objectIdIdentity) {
		this.objectIdIdentity = objectIdIdentity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclObjectIdentity")
	public Set getAclObjectIdentities() {
		return this.aclObjectIdentities;
	}

	public void setAclObjectIdentities(Set aclObjectIdentities) {
		this.aclObjectIdentities = aclObjectIdentities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclObjectIdentity")
	public Set getAclEntries() {
		return this.aclEntries;
	}

	public void setAclEntries(Set aclEntries) {
		this.aclEntries = aclEntries;
	}

}
