package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AclSid generated by hbm2java
 */
@Entity
@Table(name = "acl_sid", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "sid", "principal" }))
public class AclSid implements java.io.Serializable {

	private long id;
	private boolean principal;
	private String sid;
	private Set aclEntries = new HashSet(0);
	private Set aclObjectIdentities = new HashSet(0);

	public AclSid() {
	}

	public AclSid(long id, boolean principal, String sid) {
		this.id = id;
		this.principal = principal;
		this.sid = sid;
	}

	public AclSid(long id, boolean principal, String sid, Set aclEntries, Set aclObjectIdentities) {
		this.id = id;
		this.principal = principal;
		this.sid = sid;
		this.aclEntries = aclEntries;
		this.aclObjectIdentities = aclObjectIdentities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "principal", nullable = false)
	public boolean isPrincipal() {
		return this.principal;
	}

	public void setPrincipal(boolean principal) {
		this.principal = principal;
	}

	@Column(name = "sid", nullable = false)
	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclSid")
	public Set getAclEntries() {
		return this.aclEntries;
	}

	public void setAclEntries(Set aclEntries) {
		this.aclEntries = aclEntries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aclSid")
	public Set getAclObjectIdentities() {
		return this.aclObjectIdentities;
	}

	public void setAclObjectIdentities(Set aclObjectIdentities) {
		this.aclObjectIdentities = aclObjectIdentities;
	}

}
