package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AuthenticationToken generated by hbm2java
 */
@Entity
@Table(name = "authentication_token", schema = "public")
public class AuthenticationToken implements java.io.Serializable {

	private long id;
	private long version;
	private String email;
	private String tokenValue;

	public AuthenticationToken() {
	}

	public AuthenticationToken(long id, String email, String tokenValue) {
		this.id = id;
		this.email = email;
		this.tokenValue = tokenValue;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "token_value", nullable = false)
	public String getTokenValue() {
		return this.tokenValue;
	}

	public void setTokenValue(String tokenValue) {
		this.tokenValue = tokenValue;
	}

}
