package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * BlockedMails generated by hbm2java
 */
@Entity
@Table(name = "blocked_mails", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class BlockedMails implements java.io.Serializable {

	private long id;
	private long version;
	private String email;

	public BlockedMails() {
	}

	public BlockedMails(long id, String email) {
		this.id = id;
		this.email = email;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
