package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar", schema = "public")
public class Calendar implements java.io.Serializable {

	private Date calendarDate;

	public Calendar() {
	}

	public Calendar(Date calendarDate) {
		this.calendarDate = calendarDate;
	}

	@Id

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "calendar_date", length = 29)
	public Date getCalendarDate() {
		return this.calendarDate;
	}

	public void setCalendarDate(Date calendarDate) {
		this.calendarDate = calendarDate;
	}

}
