package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChecklistsObservation generated by hbm2java
 */
@Entity
@Table(name = "checklists_observation", schema = "public")
public class ChecklistsObservation implements java.io.Serializable {

	private ChecklistsObservationId id;
	private Observation observation;

	public ChecklistsObservation() {
	}

	public ChecklistsObservation(ChecklistsObservationId id) {
		this.id = id;
	}

	public ChecklistsObservation(ChecklistsObservationId id, Observation observation) {
		this.id = id;
		this.observation = observation;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "checklistsObservationsId", column = @Column(name = "checklists_observations_id")),
			@AttributeOverride(name = "observationId", column = @Column(name = "observation_id")),
			@AttributeOverride(name = "observationsIdx", column = @Column(name = "observations_idx")) })
	public ChecklistsObservationId getId() {
		return this.id;
	}

	public void setId(ChecklistsObservationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observation_id", insertable = false, updatable = false)
	public Observation getObservation() {
		return this.observation;
	}

	public void setObservation(Observation observation) {
		this.observation = observation;
	}

}
