package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChecklistsObservationId generated by hbm2java
 */
@Embeddable
public class ChecklistsObservationId implements java.io.Serializable {

	private Long checklistsObservationsId;
	private Long observationId;
	private Integer observationsIdx;

	public ChecklistsObservationId() {
	}

	public ChecklistsObservationId(Long checklistsObservationsId, Long observationId, Integer observationsIdx) {
		this.checklistsObservationsId = checklistsObservationsId;
		this.observationId = observationId;
		this.observationsIdx = observationsIdx;
	}

	@Column(name = "checklists_observations_id")
	public Long getChecklistsObservationsId() {
		return this.checklistsObservationsId;
	}

	public void setChecklistsObservationsId(Long checklistsObservationsId) {
		this.checklistsObservationsId = checklistsObservationsId;
	}

	@Column(name = "observation_id")
	public Long getObservationId() {
		return this.observationId;
	}

	public void setObservationId(Long observationId) {
		this.observationId = observationId;
	}

	@Column(name = "observations_idx")
	public Integer getObservationsIdx() {
		return this.observationsIdx;
	}

	public void setObservationsIdx(Integer observationsIdx) {
		this.observationsIdx = observationsIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChecklistsObservationId))
			return false;
		ChecklistsObservationId castOther = (ChecklistsObservationId) other;

		return ((this.getChecklistsObservationsId() == castOther.getChecklistsObservationsId())
				|| (this.getChecklistsObservationsId() != null && castOther.getChecklistsObservationsId() != null
						&& this.getChecklistsObservationsId().equals(castOther.getChecklistsObservationsId())))
				&& ((this.getObservationId() == castOther.getObservationId())
						|| (this.getObservationId() != null && castOther.getObservationId() != null
								&& this.getObservationId().equals(castOther.getObservationId())))
				&& ((this.getObservationsIdx() == castOther.getObservationsIdx())
						|| (this.getObservationsIdx() != null && castOther.getObservationsIdx() != null
								&& this.getObservationsIdx().equals(castOther.getObservationsIdx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getChecklistsObservationsId() == null ? 0 : this.getChecklistsObservationsId().hashCode());
		result = 37 * result + (getObservationId() == null ? 0 : this.getObservationId().hashCode());
		result = 37 * result + (getObservationsIdx() == null ? 0 : this.getObservationsIdx().hashCode());
		return result;
	}

}
