package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChecklistsDistrictsId generated by hbm2java
 */
@Embeddable
public class ChecklistsDistrictsId implements java.io.Serializable {

	private Long checklistsId;
	private String districtsString;

	public ChecklistsDistrictsId() {
	}

	public ChecklistsDistrictsId(Long checklistsId, String districtsString) {
		this.checklistsId = checklistsId;
		this.districtsString = districtsString;
	}

	@Column(name = "checklists_id")
	public Long getChecklistsId() {
		return this.checklistsId;
	}

	public void setChecklistsId(Long checklistsId) {
		this.checklistsId = checklistsId;
	}

	@Column(name = "districts_string")
	public String getDistrictsString() {
		return this.districtsString;
	}

	public void setDistrictsString(String districtsString) {
		this.districtsString = districtsString;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChecklistsDistrictsId))
			return false;
		ChecklistsDistrictsId castOther = (ChecklistsDistrictsId) other;

		return ((this.getChecklistsId() == castOther.getChecklistsId()) || (this.getChecklistsId() != null
				&& castOther.getChecklistsId() != null && this.getChecklistsId().equals(castOther.getChecklistsId())))
				&& ((this.getDistrictsString() == castOther.getDistrictsString())
						|| (this.getDistrictsString() != null && castOther.getDistrictsString() != null
								&& this.getDistrictsString().equals(castOther.getDistrictsString())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getChecklistsId() == null ? 0 : this.getChecklistsId().hashCode());
		result = 37 * result + (getDistrictsString() == null ? 0 : this.getDistrictsString().hashCode());
		return result;
	}

}
