package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Checklists generated by hbm2java
 */
@Entity
@Table(name = "checklists", schema = "public")
public class Checklists implements java.io.Serializable {

	private long id;
	private Observation observation;
	private Date publicationDate;
	private String rawChecklist;
	private String refText;
	private String reservesValue;
	private String sourceText;
	private int speciesCount;
	private String title;
	private String columns;
	private String commonNameColumn;
	private String sciNameColumn;
	private Long drupalId;
	private Set checklistsStateses = new HashSet(0);
	private Set checklistsContributors = new HashSet(0);
	private Set checklistsDistrictses = new HashSet(0);
	private Set checklistsTalukases = new HashSet(0);
	private Set suserObservationses = new HashSet(0);

	public Checklists() {
	}

	public Checklists(Observation observation, int speciesCount, String title, String columns) {
		this.observation = observation;
		this.speciesCount = speciesCount;
		this.title = title;
		this.columns = columns;
	}

	public Checklists(Observation observation, Date publicationDate, String rawChecklist, String refText,
			String reservesValue, String sourceText, int speciesCount, String title, String columns,
			String commonNameColumn, String sciNameColumn, Long drupalId, Set checklistsStateses,
			Set checklistsContributors, Set checklistsDistrictses, Set checklistsTalukases, Set suserObservationses) {
		this.observation = observation;
		this.publicationDate = publicationDate;
		this.rawChecklist = rawChecklist;
		this.refText = refText;
		this.reservesValue = reservesValue;
		this.sourceText = sourceText;
		this.speciesCount = speciesCount;
		this.title = title;
		this.columns = columns;
		this.commonNameColumn = commonNameColumn;
		this.sciNameColumn = sciNameColumn;
		this.drupalId = drupalId;
		this.checklistsStateses = checklistsStateses;
		this.checklistsContributors = checklistsContributors;
		this.checklistsDistrictses = checklistsDistrictses;
		this.checklistsTalukases = checklistsTalukases;
		this.suserObservationses = suserObservationses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "observation"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Observation getObservation() {
		return this.observation;
	}

	public void setObservation(Observation observation) {
		this.observation = observation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publication_date", length = 29)
	public Date getPublicationDate() {
		return this.publicationDate;
	}

	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	@Column(name = "raw_checklist")
	public String getRawChecklist() {
		return this.rawChecklist;
	}

	public void setRawChecklist(String rawChecklist) {
		this.rawChecklist = rawChecklist;
	}

	@Column(name = "ref_text")
	public String getRefText() {
		return this.refText;
	}

	public void setRefText(String refText) {
		this.refText = refText;
	}

	@Column(name = "reserves_value")
	public String getReservesValue() {
		return this.reservesValue;
	}

	public void setReservesValue(String reservesValue) {
		this.reservesValue = reservesValue;
	}

	@Column(name = "source_text")
	public String getSourceText() {
		return this.sourceText;
	}

	public void setSourceText(String sourceText) {
		this.sourceText = sourceText;
	}

	@Column(name = "species_count", nullable = false)
	public int getSpeciesCount() {
		return this.speciesCount;
	}

	public void setSpeciesCount(int speciesCount) {
		this.speciesCount = speciesCount;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "columns", nullable = false)
	public String getColumns() {
		return this.columns;
	}

	public void setColumns(String columns) {
		this.columns = columns;
	}

	@Column(name = "common_name_column")
	public String getCommonNameColumn() {
		return this.commonNameColumn;
	}

	public void setCommonNameColumn(String commonNameColumn) {
		this.commonNameColumn = commonNameColumn;
	}

	@Column(name = "sci_name_column")
	public String getSciNameColumn() {
		return this.sciNameColumn;
	}

	public void setSciNameColumn(String sciNameColumn) {
		this.sciNameColumn = sciNameColumn;
	}

	@Column(name = "drupal_id")
	public Long getDrupalId() {
		return this.drupalId;
	}

	public void setDrupalId(Long drupalId) {
		this.drupalId = drupalId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checklists")
	public Set getChecklistsStateses() {
		return this.checklistsStateses;
	}

	public void setChecklistsStateses(Set checklistsStateses) {
		this.checklistsStateses = checklistsStateses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checklists")
	public Set getChecklistsContributors() {
		return this.checklistsContributors;
	}

	public void setChecklistsContributors(Set checklistsContributors) {
		this.checklistsContributors = checklistsContributors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checklists")
	public Set getChecklistsDistrictses() {
		return this.checklistsDistrictses;
	}

	public void setChecklistsDistrictses(Set checklistsDistrictses) {
		this.checklistsDistrictses = checklistsDistrictses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checklists")
	public Set getChecklistsTalukases() {
		return this.checklistsTalukases;
	}

	public void setChecklistsTalukases(Set checklistsTalukases) {
		this.checklistsTalukases = checklistsTalukases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "checklists")
	public Set getSuserObservationses() {
		return this.suserObservationses;
	}

	public void setSuserObservationses(Set suserObservationses) {
		this.suserObservationses = suserObservationses;
	}

}
