package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChecklistSpeciesViewId generated by hbm2java
 */
@Embeddable
public class ChecklistSpeciesViewId implements java.io.Serializable {

	private Long id;
	private String speciesName;

	public ChecklistSpeciesViewId() {
	}

	public ChecklistSpeciesViewId(Long id, String speciesName) {
		this.id = id;
		this.speciesName = speciesName;
	}

	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "species_name")
	public String getSpeciesName() {
		return this.speciesName;
	}

	public void setSpeciesName(String speciesName) {
		this.speciesName = speciesName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChecklistSpeciesViewId))
			return false;
		ChecklistSpeciesViewId castOther = (ChecklistSpeciesViewId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getSpeciesName() == castOther.getSpeciesName())
						|| (this.getSpeciesName() != null && castOther.getSpeciesName() != null
								&& this.getSpeciesName().equals(castOther.getSpeciesName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getSpeciesName() == null ? 0 : this.getSpeciesName().hashCode());
		return result;
	}

}
