package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChecklistsContributor generated by hbm2java
 */
@Entity
@Table(name = "checklists_contributor", schema = "public")
public class ChecklistsContributor implements java.io.Serializable {

	private ChecklistsContributorId id;
	private Checklists checklists;
	private Contributor contributor;

	public ChecklistsContributor() {
	}

	public ChecklistsContributor(ChecklistsContributorId id) {
		this.id = id;
	}

	public ChecklistsContributor(ChecklistsContributorId id, Checklists checklists, Contributor contributor) {
		this.id = id;
		this.checklists = checklists;
		this.contributor = contributor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "checklistsAttributionsId", column = @Column(name = "checklists_attributions_id")),
			@AttributeOverride(name = "contributorId", column = @Column(name = "contributor_id")) })
	public ChecklistsContributorId getId() {
		return this.id;
	}

	public void setId(ChecklistsContributorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "checklists_attributions_id", insertable = false, updatable = false)
	public Checklists getChecklists() {
		return this.checklists;
	}

	public void setChecklists(Checklists checklists) {
		this.checklists = checklists;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contributor_id", insertable = false, updatable = false)
	public Contributor getContributor() {
		return this.contributor;
	}

	public void setContributor(Contributor contributor) {
		this.contributor = contributor;
	}

}
