package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChecklistsTalukasId generated by hbm2java
 */
@Embeddable
public class ChecklistsTalukasId implements java.io.Serializable {

	private Long checklistsId;
	private String talukasString;

	public ChecklistsTalukasId() {
	}

	public ChecklistsTalukasId(Long checklistsId, String talukasString) {
		this.checklistsId = checklistsId;
		this.talukasString = talukasString;
	}

	@Column(name = "checklists_id")
	public Long getChecklistsId() {
		return this.checklistsId;
	}

	public void setChecklistsId(Long checklistsId) {
		this.checklistsId = checklistsId;
	}

	@Column(name = "talukas_string")
	public String getTalukasString() {
		return this.talukasString;
	}

	public void setTalukasString(String talukasString) {
		this.talukasString = talukasString;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChecklistsTalukasId))
			return false;
		ChecklistsTalukasId castOther = (ChecklistsTalukasId) other;

		return ((this.getChecklistsId() == castOther.getChecklistsId()) || (this.getChecklistsId() != null
				&& castOther.getChecklistsId() != null && this.getChecklistsId().equals(castOther.getChecklistsId())))
				&& ((this.getTalukasString() == castOther.getTalukasString())
						|| (this.getTalukasString() != null && castOther.getTalukasString() != null
								&& this.getTalukasString().equals(castOther.getTalukasString())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getChecklistsId() == null ? 0 : this.getChecklistsId().hashCode());
		result = 37 * result + (getTalukasString() == null ? 0 : this.getTalukasString().hashCode());
		return result;
	}

}
