package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChecklistSpeciesView generated by hbm2java
 */
@Entity
@Table(name = "checklist_species_view", schema = "public")
public class ChecklistSpeciesView implements java.io.Serializable {

	private ChecklistSpeciesViewId id;

	public ChecklistSpeciesView() {
	}

	public ChecklistSpeciesView(ChecklistSpeciesViewId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "speciesName", column = @Column(name = "species_name")) })
	public ChecklistSpeciesViewId getId() {
		return this.id;
	}

	public void setId(ChecklistSpeciesViewId id) {
		this.id = id;
	}

}
