package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ChecklistSpeciesLocations generated by hbm2java
 */
@Entity
@Table(name = "checklist_species_locations", schema = "public")
public class ChecklistSpeciesLocations implements java.io.Serializable {

	private ChecklistSpeciesLocationsId id;

	public ChecklistSpeciesLocations() {
	}

	public ChecklistSpeciesLocations(ChecklistSpeciesLocationsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "source", column = @Column(name = "source")),
			@AttributeOverride(name = "title", column = @Column(name = "title")),
			@AttributeOverride(name = "speciesName", column = @Column(name = "species_name")),
			@AttributeOverride(name = "topology", column = @Column(name = "topology")) })
	public ChecklistSpeciesLocationsId getId() {
		return this.id;
	}

	public void setId(ChecklistSpeciesLocationsId id) {
		this.id = id;
	}

}
