package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommentSuser generated by hbm2java
 */
@Entity
@Table(name = "comment_suser", schema = "public")
public class CommentSuser implements java.io.Serializable {

	private CommentSuserId id;
	private Comment comment;
	private Suser suser;

	public CommentSuser() {
	}

	public CommentSuser(CommentSuserId id) {
		this.id = id;
	}

	public CommentSuser(CommentSuserId id, Comment comment, Suser suser) {
		this.id = id;
		this.comment = comment;
		this.suser = suser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "commentLikesId", column = @Column(name = "comment_likes_id")),
			@AttributeOverride(name = "suserId", column = @Column(name = "suser_id")) })
	public CommentSuserId getId() {
		return this.id;
	}

	public void setId(CommentSuserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_likes_id", insertable = false, updatable = false)
	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suser_id", insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

}
