package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", schema = "public")
public class Comment implements java.io.Serializable {

	private long id;
	private long version;
	private Language language;
	private Suser suser;
	private String body;
	private long commentHolderId;
	private String commentHolderType;
	private Date dateCreated;
	private Date lastUpdated;
	private long rootHolderId;
	private String rootHolderType;
	private Long mainParentId;
	private Long parentId;
	private String subject;
	private Set commentResources = new HashSet(0);
	private Set commentSusers = new HashSet(0);

	public Comment() {
	}

	public Comment(long id, Language language, Suser suser, String body, long commentHolderId, String commentHolderType,
			Date dateCreated, Date lastUpdated, long rootHolderId, String rootHolderType) {
		this.id = id;
		this.language = language;
		this.suser = suser;
		this.body = body;
		this.commentHolderId = commentHolderId;
		this.commentHolderType = commentHolderType;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.rootHolderId = rootHolderId;
		this.rootHolderType = rootHolderType;
	}

	public Comment(long id, Language language, Suser suser, String body, long commentHolderId, String commentHolderType,
			Date dateCreated, Date lastUpdated, long rootHolderId, String rootHolderType, Long mainParentId,
			Long parentId, String subject, Set commentResources, Set commentSusers) {
		this.id = id;
		this.language = language;
		this.suser = suser;
		this.body = body;
		this.commentHolderId = commentHolderId;
		this.commentHolderType = commentHolderType;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.rootHolderId = rootHolderId;
		this.rootHolderType = rootHolderType;
		this.mainParentId = mainParentId;
		this.parentId = parentId;
		this.subject = subject;
		this.commentResources = commentResources;
		this.commentSusers = commentSusers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Column(name = "body", nullable = false)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "comment_holder_id", nullable = false)
	public long getCommentHolderId() {
		return this.commentHolderId;
	}

	public void setCommentHolderId(long commentHolderId) {
		this.commentHolderId = commentHolderId;
	}

	@Column(name = "comment_holder_type", nullable = false)
	public String getCommentHolderType() {
		return this.commentHolderType;
	}

	public void setCommentHolderType(String commentHolderType) {
		this.commentHolderType = commentHolderType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 29)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "root_holder_id", nullable = false)
	public long getRootHolderId() {
		return this.rootHolderId;
	}

	public void setRootHolderId(long rootHolderId) {
		this.rootHolderId = rootHolderId;
	}

	@Column(name = "root_holder_type", nullable = false)
	public String getRootHolderType() {
		return this.rootHolderType;
	}

	public void setRootHolderType(String rootHolderType) {
		this.rootHolderType = rootHolderType;
	}

	@Column(name = "main_parent_id")
	public Long getMainParentId() {
		return this.mainParentId;
	}

	public void setMainParentId(Long mainParentId) {
		this.mainParentId = mainParentId;
	}

	@Column(name = "parent_id")
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "subject")
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comment")
	public Set getCommentResources() {
		return this.commentResources;
	}

	public void setCommentResources(Set commentResources) {
		this.commentResources = commentResources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comment")
	public Set getCommentSusers() {
		return this.commentSusers;
	}

	public void setCommentSusers(Set commentSusers) {
		this.commentSusers = commentSusers;
	}

}
