package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentSuserId generated by hbm2java
 */
@Embeddable
public class CommentSuserId implements java.io.Serializable {

	private Long commentLikesId;
	private Long suserId;

	public CommentSuserId() {
	}

	public CommentSuserId(Long commentLikesId, Long suserId) {
		this.commentLikesId = commentLikesId;
		this.suserId = suserId;
	}

	@Column(name = "comment_likes_id")
	public Long getCommentLikesId() {
		return this.commentLikesId;
	}

	public void setCommentLikesId(Long commentLikesId) {
		this.commentLikesId = commentLikesId;
	}

	@Column(name = "suser_id")
	public Long getSuserId() {
		return this.suserId;
	}

	public void setSuserId(Long suserId) {
		this.suserId = suserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentSuserId))
			return false;
		CommentSuserId castOther = (CommentSuserId) other;

		return ((this.getCommentLikesId() == castOther.getCommentLikesId())
				|| (this.getCommentLikesId() != null && castOther.getCommentLikesId() != null
						&& this.getCommentLikesId().equals(castOther.getCommentLikesId())))
				&& ((this.getSuserId() == castOther.getSuserId()) || (this.getSuserId() != null
						&& castOther.getSuserId() != null && this.getSuserId().equals(castOther.getSuserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCommentLikesId() == null ? 0 : this.getCommentLikesId().hashCode());
		result = 37 * result + (getSuserId() == null ? 0 : this.getSuserId().hashCode());
		return result;
	}

}
