package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommonNamesSuserId generated by hbm2java
 */
@Embeddable
public class CommonNamesSuserId implements java.io.Serializable {

	private Long commonNamesContributorsId;
	private Long suserId;
	private Integer contributorsIdx;
	private Long commonNamesCuratorsId;
	private Integer curatorsIdx;

	public CommonNamesSuserId() {
	}

	public CommonNamesSuserId(Long commonNamesContributorsId, Long suserId, Integer contributorsIdx,
			Long commonNamesCuratorsId, Integer curatorsIdx) {
		this.commonNamesContributorsId = commonNamesContributorsId;
		this.suserId = suserId;
		this.contributorsIdx = contributorsIdx;
		this.commonNamesCuratorsId = commonNamesCuratorsId;
		this.curatorsIdx = curatorsIdx;
	}

	@Column(name = "common_names_contributors_id")
	public Long getCommonNamesContributorsId() {
		return this.commonNamesContributorsId;
	}

	public void setCommonNamesContributorsId(Long commonNamesContributorsId) {
		this.commonNamesContributorsId = commonNamesContributorsId;
	}

	@Column(name = "suser_id")
	public Long getSuserId() {
		return this.suserId;
	}

	public void setSuserId(Long suserId) {
		this.suserId = suserId;
	}

	@Column(name = "contributors_idx")
	public Integer getContributorsIdx() {
		return this.contributorsIdx;
	}

	public void setContributorsIdx(Integer contributorsIdx) {
		this.contributorsIdx = contributorsIdx;
	}

	@Column(name = "common_names_curators_id")
	public Long getCommonNamesCuratorsId() {
		return this.commonNamesCuratorsId;
	}

	public void setCommonNamesCuratorsId(Long commonNamesCuratorsId) {
		this.commonNamesCuratorsId = commonNamesCuratorsId;
	}

	@Column(name = "curators_idx")
	public Integer getCuratorsIdx() {
		return this.curatorsIdx;
	}

	public void setCuratorsIdx(Integer curatorsIdx) {
		this.curatorsIdx = curatorsIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommonNamesSuserId))
			return false;
		CommonNamesSuserId castOther = (CommonNamesSuserId) other;

		return ((this.getCommonNamesContributorsId() == castOther.getCommonNamesContributorsId())
				|| (this.getCommonNamesContributorsId() != null && castOther.getCommonNamesContributorsId() != null
						&& this.getCommonNamesContributorsId().equals(castOther.getCommonNamesContributorsId())))
				&& ((this.getSuserId() == castOther.getSuserId()) || (this.getSuserId() != null
						&& castOther.getSuserId() != null && this.getSuserId().equals(castOther.getSuserId())))
				&& ((this.getContributorsIdx() == castOther.getContributorsIdx())
						|| (this.getContributorsIdx() != null && castOther.getContributorsIdx() != null
								&& this.getContributorsIdx().equals(castOther.getContributorsIdx())))
				&& ((this.getCommonNamesCuratorsId() == castOther.getCommonNamesCuratorsId())
						|| (this.getCommonNamesCuratorsId() != null && castOther.getCommonNamesCuratorsId() != null
								&& this.getCommonNamesCuratorsId().equals(castOther.getCommonNamesCuratorsId())))
				&& ((this.getCuratorsIdx() == castOther.getCuratorsIdx())
						|| (this.getCuratorsIdx() != null && castOther.getCuratorsIdx() != null
								&& this.getCuratorsIdx().equals(castOther.getCuratorsIdx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCommonNamesContributorsId() == null ? 0 : this.getCommonNamesContributorsId().hashCode());
		result = 37 * result + (getSuserId() == null ? 0 : this.getSuserId().hashCode());
		result = 37 * result + (getContributorsIdx() == null ? 0 : this.getContributorsIdx().hashCode());
		result = 37 * result + (getCommonNamesCuratorsId() == null ? 0 : this.getCommonNamesCuratorsId().hashCode());
		result = 37 * result + (getCuratorsIdx() == null ? 0 : this.getCuratorsIdx().hashCode());
		return result;
	}

}
