package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contributor generated by hbm2java
 */
@Entity
@Table(name = "contributor", schema = "public")
public class Contributor implements java.io.Serializable {

	private long id;
	private Suser suser;
	private String name;
	private Set checklistsContributors = new HashSet(0);
	private Set resourceContributors = new HashSet(0);
	private Set speciesFieldContributors = new HashSet(0);

	public Contributor() {
	}

	public Contributor(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Contributor(long id, Suser suser, String name, Set checklistsContributors, Set resourceContributors,
			Set speciesFieldContributors) {
		this.id = id;
		this.suser = suser;
		this.name = name;
		this.checklistsContributors = checklistsContributors;
		this.resourceContributors = resourceContributors;
		this.speciesFieldContributors = speciesFieldContributors;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contributor")
	public Set getChecklistsContributors() {
		return this.checklistsContributors;
	}

	public void setChecklistsContributors(Set checklistsContributors) {
		this.checklistsContributors = checklistsContributors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contributor")
	public Set getResourceContributors() {
		return this.resourceContributors;
	}

	public void setResourceContributors(Set resourceContributors) {
		this.resourceContributors = resourceContributors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contributor")
	public Set getSpeciesFieldContributors() {
		return this.speciesFieldContributors;
	}

	public void setSpeciesFieldContributors(Set speciesFieldContributors) {
		this.speciesFieldContributors = speciesFieldContributors;
	}

}
