package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "two_letter_code"))
public class Country implements java.io.Serializable {

	private long id;
	private String countryName;
	private String twoLetterCode;
	private Set speciesFields = new HashSet(0);

	public Country() {
	}

	public Country(long id, String countryName, String twoLetterCode) {
		this.id = id;
		this.countryName = countryName;
		this.twoLetterCode = twoLetterCode;
	}

	public Country(long id, String countryName, String twoLetterCode, Set speciesFields) {
		this.id = id;
		this.countryName = countryName;
		this.twoLetterCode = twoLetterCode;
		this.speciesFields = speciesFields;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "country_name", nullable = false)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "two_letter_code", unique = true, nullable = false)
	public String getTwoLetterCode() {
		return this.twoLetterCode;
	}

	public void setTwoLetterCode(String twoLetterCode) {
		this.twoLetterCode = twoLetterCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set getSpeciesFields() {
		return this.speciesFields;
	}

	public void setSpeciesFields(Set speciesFields) {
		this.speciesFields = speciesFields;
	}

}
