package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CoverageHabitatId generated by hbm2java
 */
@Embeddable
public class CoverageHabitatId implements java.io.Serializable {

	private Long coverageHabitatsId;
	private Long habitatId;

	public CoverageHabitatId() {
	}

	public CoverageHabitatId(Long coverageHabitatsId, Long habitatId) {
		this.coverageHabitatsId = coverageHabitatsId;
		this.habitatId = habitatId;
	}

	@Column(name = "coverage_habitats_id")
	public Long getCoverageHabitatsId() {
		return this.coverageHabitatsId;
	}

	public void setCoverageHabitatsId(Long coverageHabitatsId) {
		this.coverageHabitatsId = coverageHabitatsId;
	}

	@Column(name = "habitat_id")
	public Long getHabitatId() {
		return this.habitatId;
	}

	public void setHabitatId(Long habitatId) {
		this.habitatId = habitatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CoverageHabitatId))
			return false;
		CoverageHabitatId castOther = (CoverageHabitatId) other;

		return ((this.getCoverageHabitatsId() == castOther.getCoverageHabitatsId())
				|| (this.getCoverageHabitatsId() != null && castOther.getCoverageHabitatsId() != null
						&& this.getCoverageHabitatsId().equals(castOther.getCoverageHabitatsId())))
				&& ((this.getHabitatId() == castOther.getHabitatId()) || (this.getHabitatId() != null
						&& castOther.getHabitatId() != null && this.getHabitatId().equals(castOther.getHabitatId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoverageHabitatsId() == null ? 0 : this.getCoverageHabitatsId().hashCode());
		result = 37 * result + (getHabitatId() == null ? 0 : this.getHabitatId().hashCode());
		return result;
	}

}
