package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CoverageSpeciesGroupId generated by hbm2java
 */
@Embeddable
public class CoverageSpeciesGroupId implements java.io.Serializable {

	private Long coverageSpeciesGroupsId;
	private Long speciesGroupId;

	public CoverageSpeciesGroupId() {
	}

	public CoverageSpeciesGroupId(Long coverageSpeciesGroupsId, Long speciesGroupId) {
		this.coverageSpeciesGroupsId = coverageSpeciesGroupsId;
		this.speciesGroupId = speciesGroupId;
	}

	@Column(name = "coverage_species_groups_id")
	public Long getCoverageSpeciesGroupsId() {
		return this.coverageSpeciesGroupsId;
	}

	public void setCoverageSpeciesGroupsId(Long coverageSpeciesGroupsId) {
		this.coverageSpeciesGroupsId = coverageSpeciesGroupsId;
	}

	@Column(name = "species_group_id")
	public Long getSpeciesGroupId() {
		return this.speciesGroupId;
	}

	public void setSpeciesGroupId(Long speciesGroupId) {
		this.speciesGroupId = speciesGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CoverageSpeciesGroupId))
			return false;
		CoverageSpeciesGroupId castOther = (CoverageSpeciesGroupId) other;

		return ((this.getCoverageSpeciesGroupsId() == castOther.getCoverageSpeciesGroupsId())
				|| (this.getCoverageSpeciesGroupsId() != null && castOther.getCoverageSpeciesGroupsId() != null
						&& this.getCoverageSpeciesGroupsId().equals(castOther.getCoverageSpeciesGroupsId())))
				&& ((this.getSpeciesGroupId() == castOther.getSpeciesGroupId())
						|| (this.getSpeciesGroupId() != null && castOther.getSpeciesGroupId() != null
								&& this.getSpeciesGroupId().equals(castOther.getSpeciesGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCoverageSpeciesGroupsId() == null ? 0 : this.getCoverageSpeciesGroupsId().hashCode());
		result = 37 * result + (getSpeciesGroupId() == null ? 0 : this.getSpeciesGroupId().hashCode());
		return result;
	}

}
