package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * CustomField generated by hbm2java
 */
@Entity
@Table(name = "custom_field", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "user_group_id",
		"name" }))
public class CustomField implements java.io.Serializable {

	private long id;
	private long version;
	private UserGroup userGroup;
	private Suser suser;
	private boolean allowedMultiple;
	private String dataType;
	private String defaultValue;
	private int displayOrder;
	private boolean isMandatory;
	private String name;
	private String notes;
	private String options;
	private Boolean allowedParticipation;

	public CustomField() {
	}

	public CustomField(long id, UserGroup userGroup, Suser suser, boolean allowedMultiple, String dataType,
			int displayOrder, boolean isMandatory, String name) {
		this.id = id;
		this.userGroup = userGroup;
		this.suser = suser;
		this.allowedMultiple = allowedMultiple;
		this.dataType = dataType;
		this.displayOrder = displayOrder;
		this.isMandatory = isMandatory;
		this.name = name;
	}

	public CustomField(long id, UserGroup userGroup, Suser suser, boolean allowedMultiple, String dataType,
			String defaultValue, int displayOrder, boolean isMandatory, String name, String notes, String options,
			Boolean allowedParticipation) {
		this.id = id;
		this.userGroup = userGroup;
		this.suser = suser;
		this.allowedMultiple = allowedMultiple;
		this.dataType = dataType;
		this.defaultValue = defaultValue;
		this.displayOrder = displayOrder;
		this.isMandatory = isMandatory;
		this.name = name;
		this.notes = notes;
		this.options = options;
		this.allowedParticipation = allowedParticipation;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_group_id", nullable = false)
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Column(name = "allowed_multiple", nullable = false)
	public boolean isAllowedMultiple() {
		return this.allowedMultiple;
	}

	public void setAllowedMultiple(boolean allowedMultiple) {
		this.allowedMultiple = allowedMultiple;
	}

	@Column(name = "data_type", nullable = false)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "default_value")
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "display_order", nullable = false)
	public int getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "is_mandatory", nullable = false)
	public boolean isIsMandatory() {
		return this.isMandatory;
	}

	public void setIsMandatory(boolean isMandatory) {
		this.isMandatory = isMandatory;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "options")
	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	@Column(name = "allowed_participation")
	public Boolean getAllowedParticipation() {
		return this.allowedParticipation;
	}

	public void setAllowedParticipation(Boolean allowedParticipation) {
		this.allowedParticipation = allowedParticipation;
	}

}
