package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * DataLink generated by hbm2java
 */
@Entity
@Table(name = "data_link", schema = "public")
public class DataLink implements java.io.Serializable {

	private long id;
	private long version;
	private String description;
	private String url;
	private Set projectDataLinks = new HashSet(0);

	public DataLink() {
	}

	public DataLink(long id) {
		this.id = id;
	}

	public DataLink(long id, String description, String url, Set projectDataLinks) {
		this.id = id;
		this.description = description;
		this.url = url;
		this.projectDataLinks = projectDataLinks;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataLink")
	public Set getProjectDataLinks() {
		return this.projectDataLinks;
	}

	public void setProjectDataLinks(Set projectDataLinks) {
		this.projectDataLinks = projectDataLinks;
	}

}
