package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentHabitatId generated by hbm2java
 */
@Embeddable
public class DocumentHabitatId implements java.io.Serializable {

	private Long documentHabitatsId;
	private Long habitatId;

	public DocumentHabitatId() {
	}

	public DocumentHabitatId(Long documentHabitatsId, Long habitatId) {
		this.documentHabitatsId = documentHabitatsId;
		this.habitatId = habitatId;
	}

	@Column(name = "document_habitats_id")
	public Long getDocumentHabitatsId() {
		return this.documentHabitatsId;
	}

	public void setDocumentHabitatsId(Long documentHabitatsId) {
		this.documentHabitatsId = documentHabitatsId;
	}

	@Column(name = "habitat_id")
	public Long getHabitatId() {
		return this.habitatId;
	}

	public void setHabitatId(Long habitatId) {
		this.habitatId = habitatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentHabitatId))
			return false;
		DocumentHabitatId castOther = (DocumentHabitatId) other;

		return ((this.getDocumentHabitatsId() == castOther.getDocumentHabitatsId())
				|| (this.getDocumentHabitatsId() != null && castOther.getDocumentHabitatsId() != null
						&& this.getDocumentHabitatsId().equals(castOther.getDocumentHabitatsId())))
				&& ((this.getHabitatId() == castOther.getHabitatId()) || (this.getHabitatId() != null
						&& castOther.getHabitatId() != null && this.getHabitatId().equals(castOther.getHabitatId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDocumentHabitatsId() == null ? 0 : this.getDocumentHabitatsId().hashCode());
		result = 37 * result + (getHabitatId() == null ? 0 : this.getHabitatId().hashCode());
		return result;
	}

}
