package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DocumentHabitat generated by hbm2java
 */
@Entity
@Table(name = "document_habitat", schema = "public")
public class DocumentHabitat implements java.io.Serializable {

	private DocumentHabitatId id;
	private Document document;
	private Habitat habitat;

	public DocumentHabitat() {
	}

	public DocumentHabitat(DocumentHabitatId id) {
		this.id = id;
	}

	public DocumentHabitat(DocumentHabitatId id, Document document, Habitat habitat) {
		this.id = id;
		this.document = document;
		this.habitat = habitat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "documentHabitatsId", column = @Column(name = "document_habitats_id")),
			@AttributeOverride(name = "habitatId", column = @Column(name = "habitat_id")) })
	public DocumentHabitatId getId() {
		return this.id;
	}

	public void setId(DocumentHabitatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_habitats_id", insertable = false, updatable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "habitat_id", insertable = false, updatable = false)
	public Habitat getHabitat() {
		return this.habitat;
	}

	public void setHabitat(Habitat habitat) {
		this.habitat = habitat;
	}

}
