package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentSpeciesGroupId generated by hbm2java
 */
@Embeddable
public class DocumentSpeciesGroupId implements java.io.Serializable {

	private Long documentSpeciesGroupsId;
	private Long speciesGroupId;

	public DocumentSpeciesGroupId() {
	}

	public DocumentSpeciesGroupId(Long documentSpeciesGroupsId, Long speciesGroupId) {
		this.documentSpeciesGroupsId = documentSpeciesGroupsId;
		this.speciesGroupId = speciesGroupId;
	}

	@Column(name = "document_species_groups_id")
	public Long getDocumentSpeciesGroupsId() {
		return this.documentSpeciesGroupsId;
	}

	public void setDocumentSpeciesGroupsId(Long documentSpeciesGroupsId) {
		this.documentSpeciesGroupsId = documentSpeciesGroupsId;
	}

	@Column(name = "species_group_id")
	public Long getSpeciesGroupId() {
		return this.speciesGroupId;
	}

	public void setSpeciesGroupId(Long speciesGroupId) {
		this.speciesGroupId = speciesGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentSpeciesGroupId))
			return false;
		DocumentSpeciesGroupId castOther = (DocumentSpeciesGroupId) other;

		return ((this.getDocumentSpeciesGroupsId() == castOther.getDocumentSpeciesGroupsId())
				|| (this.getDocumentSpeciesGroupsId() != null && castOther.getDocumentSpeciesGroupsId() != null
						&& this.getDocumentSpeciesGroupsId().equals(castOther.getDocumentSpeciesGroupsId())))
				&& ((this.getSpeciesGroupId() == castOther.getSpeciesGroupId())
						|| (this.getSpeciesGroupId() != null && castOther.getSpeciesGroupId() != null
								&& this.getSpeciesGroupId().equals(castOther.getSpeciesGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDocumentSpeciesGroupsId() == null ? 0 : this.getDocumentSpeciesGroupsId().hashCode());
		result = 37 * result + (getSpeciesGroupId() == null ? 0 : this.getSpeciesGroupId().hashCode());
		return result;
	}

}
