package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * DownloadLog generated by hbm2java
 */
@Entity
@Table(name = "download_log", schema = "public")
public class DownloadLog implements java.io.Serializable {

	private long id;
	private long version;
	private Suser suser;
	private Date createdOn;
	private String filePath;
	private String filterUrl;
	private String notes;
	private String paramsMapAsText;
	private String status;
	private String type;
	private String sourceType;
	private long offsetParam;

	public DownloadLog() {
	}

	public DownloadLog(long id, Suser suser, Date createdOn, String filterUrl, String status, String type,
			long offsetParam) {
		this.id = id;
		this.suser = suser;
		this.createdOn = createdOn;
		this.filterUrl = filterUrl;
		this.status = status;
		this.type = type;
		this.offsetParam = offsetParam;
	}

	public DownloadLog(long id, Suser suser, Date createdOn, String filePath, String filterUrl, String notes,
			String paramsMapAsText, String status, String type, String sourceType, long offsetParam) {
		this.id = id;
		this.suser = suser;
		this.createdOn = createdOn;
		this.filePath = filePath;
		this.filterUrl = filterUrl;
		this.notes = notes;
		this.paramsMapAsText = paramsMapAsText;
		this.status = status;
		this.type = type;
		this.sourceType = sourceType;
		this.offsetParam = offsetParam;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 29)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "file_path")
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "filter_url", nullable = false)
	public String getFilterUrl() {
		return this.filterUrl;
	}

	public void setFilterUrl(String filterUrl) {
		this.filterUrl = filterUrl;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "params_map_as_text")
	public String getParamsMapAsText() {
		return this.paramsMapAsText;
	}

	public void setParamsMapAsText(String paramsMapAsText) {
		this.paramsMapAsText = paramsMapAsText;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "source_type")
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "offset_param", nullable = false)
	public long getOffsetParam() {
		return this.offsetParam;
	}

	public void setOffsetParam(long offsetParam) {
		this.offsetParam = offsetParam;
	}

}
