package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * FacebookUser generated by hbm2java
 */
@Entity
@Table(name = "facebook_user", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "uid"))
public class FacebookUser implements java.io.Serializable {

	private long id;
	private long version;
	private Suser suser;
	private String accessToken;
	private boolean isFirstLogin;
	private long uid;
	private Date accessTokenExpires;

	public FacebookUser() {
	}

	public FacebookUser(long id, Suser suser, String accessToken, boolean isFirstLogin, long uid) {
		this.id = id;
		this.suser = suser;
		this.accessToken = accessToken;
		this.isFirstLogin = isFirstLogin;
		this.uid = uid;
	}

	public FacebookUser(long id, Suser suser, String accessToken, boolean isFirstLogin, long uid,
			Date accessTokenExpires) {
		this.id = id;
		this.suser = suser;
		this.accessToken = accessToken;
		this.isFirstLogin = isFirstLogin;
		this.uid = uid;
		this.accessTokenExpires = accessTokenExpires;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Column(name = "access_token", nullable = false)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "is_first_login", nullable = false)
	public boolean isIsFirstLogin() {
		return this.isFirstLogin;
	}

	public void setIsFirstLogin(boolean isFirstLogin) {
		this.isFirstLogin = isFirstLogin;
	}

	@Column(name = "uid", unique = true, nullable = false)
	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "access_token_expires", length = 29)
	public Date getAccessTokenExpires() {
		return this.accessTokenExpires;
	}

	public void setAccessTokenExpires(Date accessTokenExpires) {
		this.accessTokenExpires = accessTokenExpires;
	}

}
