package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Field generated by hbm2java
 */
@Entity
@Table(name = "field", schema = "public")
public class Field implements java.io.Serializable {

	private long id;
	private Language language;
	private String category;
	private String concept;
	private String description;
	private int displayOrder;
	private String subCategory;
	private String urlIdentifier;
	private long connection;
	private Set speciesFields = new HashSet(0);
	private Set traits = new HashSet(0);

	public Field() {
	}

	public Field(long id, Language language, String concept, int displayOrder, long connection) {
		this.id = id;
		this.language = language;
		this.concept = concept;
		this.displayOrder = displayOrder;
		this.connection = connection;
	}

	public Field(long id, Language language, String category, String concept, String description, int displayOrder,
			String subCategory, String urlIdentifier, long connection, Set speciesFields, Set traits) {
		this.id = id;
		this.language = language;
		this.category = category;
		this.concept = concept;
		this.description = description;
		this.displayOrder = displayOrder;
		this.subCategory = subCategory;
		this.urlIdentifier = urlIdentifier;
		this.connection = connection;
		this.speciesFields = speciesFields;
		this.traits = traits;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "category")
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "concept", nullable = false)
	public String getConcept() {
		return this.concept;
	}

	public void setConcept(String concept) {
		this.concept = concept;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "display_order", nullable = false)
	public int getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(int displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "sub_category")
	public String getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(String subCategory) {
		this.subCategory = subCategory;
	}

	@Column(name = "url_identifier")
	public String getUrlIdentifier() {
		return this.urlIdentifier;
	}

	public void setUrlIdentifier(String urlIdentifier) {
		this.urlIdentifier = urlIdentifier;
	}

	@Column(name = "connection", nullable = false)
	public long getConnection() {
		return this.connection;
	}

	public void setConnection(long connection) {
		this.connection = connection;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "field")
	public Set getSpeciesFields() {
		return this.speciesFields;
	}

	public void setSpeciesFields(Set speciesFields) {
		this.speciesFields = speciesFields;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "field")
	public Set getTraits() {
		return this.traits;
	}

	public void setTraits(Set traits) {
		this.traits = traits;
	}

}
