package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Flag generated by hbm2java
 */
@Entity
@Table(name = "flag", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "author_id", "object_id",
		"object_type" }))
public class Flag implements java.io.Serializable {

	private long id;
	private long version;
	private Suser suser;
	private Date createdOn;
	private String flag;
	private String notes;
	private long objectId;
	private String objectType;

	public Flag() {
	}

	public Flag(long id, Suser suser, Date createdOn, String flag, long objectId, String objectType) {
		this.id = id;
		this.suser = suser;
		this.createdOn = createdOn;
		this.flag = flag;
		this.objectId = objectId;
		this.objectType = objectType;
	}

	public Flag(long id, Suser suser, Date createdOn, String flag, String notes, long objectId, String objectType) {
		this.id = id;
		this.suser = suser;
		this.createdOn = createdOn;
		this.flag = flag;
		this.notes = notes;
		this.objectId = objectId;
		this.objectType = objectType;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 29)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "flag", nullable = false)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "object_id", nullable = false)
	public long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(long objectId) {
		this.objectId = objectId;
	}

	@Column(name = "object_type", nullable = false)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

}
