package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * GeospatialCoverage generated by hbm2java
 */
@Entity
@Table(name = "geospatial_coverage", schema = "public")
public class GeospatialCoverage implements java.io.Serializable {

	private long id;
	private long version;
	private String description;
	private double maxLatitude;
	private double maxLongitude;
	private double minLatitude;
	private double minLongitude;

	public GeospatialCoverage() {
	}

	public GeospatialCoverage(long id, String description, double maxLatitude, double maxLongitude, double minLatitude,
			double minLongitude) {
		this.id = id;
		this.description = description;
		this.maxLatitude = maxLatitude;
		this.maxLongitude = maxLongitude;
		this.minLatitude = minLatitude;
		this.minLongitude = minLongitude;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "max_latitude", nullable = false, precision = 17, scale = 17)
	public double getMaxLatitude() {
		return this.maxLatitude;
	}

	public void setMaxLatitude(double maxLatitude) {
		this.maxLatitude = maxLatitude;
	}

	@Column(name = "max_longitude", nullable = false, precision = 17, scale = 17)
	public double getMaxLongitude() {
		return this.maxLongitude;
	}

	public void setMaxLongitude(double maxLongitude) {
		this.maxLongitude = maxLongitude;
	}

	@Column(name = "min_latitude", nullable = false, precision = 17, scale = 17)
	public double getMinLatitude() {
		return this.minLatitude;
	}

	public void setMinLatitude(double minLatitude) {
		this.minLatitude = minLatitude;
	}

	@Column(name = "min_longitude", nullable = false, precision = 17, scale = 17)
	public double getMinLongitude() {
		return this.minLongitude;
	}

	public void setMinLongitude(double minLongitude) {
		this.minLongitude = minLongitude;
	}

}
