package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Habitat generated by hbm2java
 */
@Entity
@Table(name = "habitat", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Habitat implements java.io.Serializable {

	private long id;
	private int habitatOrder;
	private String name;
	private Set specieses = new HashSet(0);
	private Set suserHabitats = new HashSet(0);
	private Set observations = new HashSet(0);
	private Set documentHabitats = new HashSet(0);
	private Set coverageHabitats = new HashSet(0);
	private Set userGroupHabitats = new HashSet(0);
	private Set documents = new HashSet(0);

	public Habitat() {
	}

	public Habitat(long id, int habitatOrder, String name) {
		this.id = id;
		this.habitatOrder = habitatOrder;
		this.name = name;
	}

	public Habitat(long id, int habitatOrder, String name, Set specieses, Set suserHabitats, Set observations,
			Set documentHabitats, Set coverageHabitats, Set userGroupHabitats, Set documents) {
		this.id = id;
		this.habitatOrder = habitatOrder;
		this.name = name;
		this.specieses = specieses;
		this.suserHabitats = suserHabitats;
		this.observations = observations;
		this.documentHabitats = documentHabitats;
		this.coverageHabitats = coverageHabitats;
		this.userGroupHabitats = userGroupHabitats;
		this.documents = documents;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "habitat_order", nullable = false)
	public int getHabitatOrder() {
		return this.habitatOrder;
	}

	public void setHabitatOrder(int habitatOrder) {
		this.habitatOrder = habitatOrder;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getSpecieses() {
		return this.specieses;
	}

	public void setSpecieses(Set specieses) {
		this.specieses = specieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getSuserHabitats() {
		return this.suserHabitats;
	}

	public void setSuserHabitats(Set suserHabitats) {
		this.suserHabitats = suserHabitats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getObservations() {
		return this.observations;
	}

	public void setObservations(Set observations) {
		this.observations = observations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getDocumentHabitats() {
		return this.documentHabitats;
	}

	public void setDocumentHabitats(Set documentHabitats) {
		this.documentHabitats = documentHabitats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getCoverageHabitats() {
		return this.coverageHabitats;
	}

	public void setCoverageHabitats(Set coverageHabitats) {
		this.coverageHabitats = coverageHabitats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getUserGroupHabitats() {
		return this.userGroupHabitats;
	}

	public void setUserGroupHabitats(Set userGroupHabitats) {
		this.userGroupHabitats = userGroupHabitats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitat")
	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}
