package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", schema = "public")
public class Location implements java.io.Serializable {

	private long id;
	private long version;
	private String corridor;
	private String siteName;
	private Set projectLocations = new HashSet(0);

	public Location() {
	}

	public Location(long id) {
		this.id = id;
	}

	public Location(long id, String corridor, String siteName, Set projectLocations) {
		this.id = id;
		this.corridor = corridor;
		this.siteName = siteName;
		this.projectLocations = projectLocations;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "corridor")
	public String getCorridor() {
		return this.corridor;
	}

	public void setCorridor(String corridor) {
		this.corridor = corridor;
	}

	@Column(name = "site_name")
	public String getSiteName() {
		return this.siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set getProjectLocations() {
		return this.projectLocations;
	}

	public void setProjectLocations(Set projectLocations) {
		this.projectLocations = projectLocations;
	}

}
