package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MapLayerFeatures generated by hbm2java
 */
@Entity
@Table(name = "map_layer_features", schema = "public")
public class MapLayerFeatures implements java.io.Serializable {

	private MapLayerFeaturesId id;

	public MapLayerFeatures() {
	}

	public MapLayerFeatures(MapLayerFeaturesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "feature", column = @Column(name = "feature")),
			@AttributeOverride(name = "topology", column = @Column(name = "topology")) })
	public MapLayerFeaturesId getId() {
		return this.id;
	}

	public void setId(MapLayerFeaturesId id) {
		this.id = id;
	}

}
