package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MissingHierarchyId generated by hbm2java
 */
@Embeddable
public class MissingHierarchyId implements java.io.Serializable {

	private Long id;
	private Long taxonid;
	private String name;
	private Integer rank;
	private String status;
	private String position;
	private String level;
	private String rankStr;

	public MissingHierarchyId() {
	}

	public MissingHierarchyId(Long id, Long taxonid, String name, Integer rank, String status, String position,
			String level, String rankStr) {
		this.id = id;
		this.taxonid = taxonid;
		this.name = name;
		this.rank = rank;
		this.status = status;
		this.position = position;
		this.level = level;
		this.rankStr = rankStr;
	}

	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "taxonid")
	public Long getTaxonid() {
		return this.taxonid;
	}

	public void setTaxonid(Long taxonid) {
		this.taxonid = taxonid;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "position")
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "level")
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "rank_str")
	public String getRankStr() {
		return this.rankStr;
	}

	public void setRankStr(String rankStr) {
		this.rankStr = rankStr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MissingHierarchyId))
			return false;
		MissingHierarchyId castOther = (MissingHierarchyId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getTaxonid() == castOther.getTaxonid()) || (this.getTaxonid() != null
						&& castOther.getTaxonid() != null && this.getTaxonid().equals(castOther.getTaxonid())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getRank() == castOther.getRank()) || (this.getRank() != null && castOther.getRank() != null
						&& this.getRank().equals(castOther.getRank())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getPosition() == castOther.getPosition()) || (this.getPosition() != null
						&& castOther.getPosition() != null && this.getPosition().equals(castOther.getPosition())))
				&& ((this.getLevel() == castOther.getLevel()) || (this.getLevel() != null
						&& castOther.getLevel() != null && this.getLevel().equals(castOther.getLevel())))
				&& ((this.getRankStr() == castOther.getRankStr()) || (this.getRankStr() != null
						&& castOther.getRankStr() != null && this.getRankStr().equals(castOther.getRankStr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getTaxonid() == null ? 0 : this.getTaxonid().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getRank() == null ? 0 : this.getRank().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getPosition() == null ? 0 : this.getPosition().hashCode());
		result = 37 * result + (getLevel() == null ? 0 : this.getLevel().hashCode());
		result = 37 * result + (getRankStr() == null ? 0 : this.getRankStr().hashCode());
		return result;
	}

}
