package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MissingHierarchy generated by hbm2java
 */
@Entity
@Table(name = "missing_hierarchy", schema = "public")
public class MissingHierarchy implements java.io.Serializable {

	private MissingHierarchyId id;

	public MissingHierarchy() {
	}

	public MissingHierarchy(MissingHierarchyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "taxonid", column = @Column(name = "taxonid")),
			@AttributeOverride(name = "name", column = @Column(name = "name")),
			@AttributeOverride(name = "rank", column = @Column(name = "rank")),
			@AttributeOverride(name = "status", column = @Column(name = "status")),
			@AttributeOverride(name = "position", column = @Column(name = "position")),
			@AttributeOverride(name = "level", column = @Column(name = "level")),
			@AttributeOverride(name = "rankStr", column = @Column(name = "rank_str")) })
	public MissingHierarchyId getId() {
		return this.id;
	}

	public void setId(MissingHierarchyId id) {
		this.id = id;
	}

}
