package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * NamePermission generated by hbm2java
 */
@Entity
@Table(name = "name_permission", schema = "public")
public class NamePermission implements java.io.Serializable {

	private long id;
	private long version;
	private Suser suser;
	private TaxonomyDefinition taxonomyDefinitionByRootNodeId;
	private TaxonomyDefinition taxonomyDefinitionByNodeId;
	private Date lastUpdated;
	private String permission;
	private int rank;

	public NamePermission() {
	}

	public NamePermission(long id, Suser suser, String permission, int rank) {
		this.id = id;
		this.suser = suser;
		this.permission = permission;
		this.rank = rank;
	}

	public NamePermission(long id, Suser suser, TaxonomyDefinition taxonomyDefinitionByRootNodeId,
			TaxonomyDefinition taxonomyDefinitionByNodeId, Date lastUpdated, String permission, int rank) {
		this.id = id;
		this.suser = suser;
		this.taxonomyDefinitionByRootNodeId = taxonomyDefinitionByRootNodeId;
		this.taxonomyDefinitionByNodeId = taxonomyDefinitionByNodeId;
		this.lastUpdated = lastUpdated;
		this.permission = permission;
		this.rank = rank;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "root_node_id")
	public TaxonomyDefinition getTaxonomyDefinitionByRootNodeId() {
		return this.taxonomyDefinitionByRootNodeId;
	}

	public void setTaxonomyDefinitionByRootNodeId(TaxonomyDefinition taxonomyDefinitionByRootNodeId) {
		this.taxonomyDefinitionByRootNodeId = taxonomyDefinitionByRootNodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "node_id")
	public TaxonomyDefinition getTaxonomyDefinitionByNodeId() {
		return this.taxonomyDefinitionByNodeId;
	}

	public void setTaxonomyDefinitionByNodeId(TaxonomyDefinition taxonomyDefinitionByNodeId) {
		this.taxonomyDefinitionByNodeId = taxonomyDefinitionByNodeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "permission", nullable = false)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@Column(name = "rank", nullable = false)
	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

}
