package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObservationReprImageId generated by hbm2java
 */
@Embeddable
public class ObservationReprImageId implements java.io.Serializable {

	private long resourceId;
	private Long reprImageId;

	public ObservationReprImageId() {
	}

	public ObservationReprImageId(long resourceId) {
		this.resourceId = resourceId;
	}

	public ObservationReprImageId(long resourceId, Long reprImageId) {
		this.resourceId = resourceId;
		this.reprImageId = reprImageId;
	}

	@Column(name = "resource_id", nullable = false)
	public long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(long resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "repr_image_id")
	public Long getReprImageId() {
		return this.reprImageId;
	}

	public void setReprImageId(Long reprImageId) {
		this.reprImageId = reprImageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObservationReprImageId))
			return false;
		ObservationReprImageId castOther = (ObservationReprImageId) other;

		return (this.getResourceId() == castOther.getResourceId())
				&& ((this.getReprImageId() == castOther.getReprImageId())
						|| (this.getReprImageId() != null && castOther.getReprImageId() != null
								&& this.getReprImageId().equals(castOther.getReprImageId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getResourceId();
		result = 37 * result + (getReprImageId() == null ? 0 : this.getReprImageId().hashCode());
		return result;
	}

}
