package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObservationReprImage generated by hbm2java
 */
@Entity
@Table(name = "observation_repr_image", schema = "public")
public class ObservationReprImage implements java.io.Serializable {

	private ObservationReprImageId id;
	private Resource resource;
	private Observation observation;

	public ObservationReprImage() {
	}

	public ObservationReprImage(ObservationReprImageId id, Resource resource) {
		this.id = id;
		this.resource = resource;
	}

	public ObservationReprImage(ObservationReprImageId id, Resource resource, Observation observation) {
		this.id = id;
		this.resource = resource;
		this.observation = observation;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resourceId", column = @Column(name = "resource_id", nullable = false)),
			@AttributeOverride(name = "reprImageId", column = @Column(name = "repr_image_id")) })
	public ObservationReprImageId getId() {
		return this.id;
	}

	public void setId(ObservationReprImageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_id", nullable = false, insertable = false, updatable = false)
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "repr_image_id", insertable = false, updatable = false)
	public Observation getObservation() {
		return this.observation;
	}

	public void setObservation(Observation observation) {
		this.observation = observation;
	}

}
