package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ObservationLocations generated by hbm2java
 */
@Entity
@Table(name = "observation_locations", schema = "public")
public class ObservationLocations implements java.io.Serializable {

	private ObservationLocationsId id;

	public ObservationLocations() {
	}

	public ObservationLocations(ObservationLocationsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "source", column = @Column(name = "source")),
			@AttributeOverride(name = "speciesName", column = @Column(name = "species_name")),
			@AttributeOverride(name = "topology", column = @Column(name = "topology")),
			@AttributeOverride(name = "lastRevised", column = @Column(name = "last_revised", length = 29)) })
	public ObservationLocationsId getId() {
		return this.id;
	}

	public void setId(ObservationLocationsId id) {
		this.id = id;
	}

}
