package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Organization generated by hbm2java
 */
@Entity
@Table(name = "organization", schema = "public")
public class Organization implements java.io.Serializable {

	private long id;
	private long version;
	private String address;
	private String city;
	private byte[] logoUrl;
	private String name;
	private String state;

	public Organization() {
	}

	public Organization(long id, String address, String city, byte[] logoUrl, String name, String state) {
		this.id = id;
		this.address = address;
		this.city = city;
		this.logoUrl = logoUrl;
		this.name = name;
		this.state = state;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "logo_url", nullable = false)
	public byte[] getLogoUrl() {
		return this.logoUrl;
	}

	public void setLogoUrl(byte[] logoUrl) {
		this.logoUrl = logoUrl;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", nullable = false)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
