package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectDocument generated by hbm2java
 */
@Entity
@Table(name = "project_document", schema = "public")
public class ProjectDocument implements java.io.Serializable {

	private ProjectDocumentId id;
	private Project projectByProjectProposalFilesId;
	private Project projectByProjectMiscFilesId;
	private Document document;
	private Project projectByProjectReportFilesId;

	public ProjectDocument() {
	}

	public ProjectDocument(ProjectDocumentId id) {
		this.id = id;
	}

	public ProjectDocument(ProjectDocumentId id, Project projectByProjectProposalFilesId,
			Project projectByProjectMiscFilesId, Document document, Project projectByProjectReportFilesId) {
		this.id = id;
		this.projectByProjectProposalFilesId = projectByProjectProposalFilesId;
		this.projectByProjectMiscFilesId = projectByProjectMiscFilesId;
		this.document = document;
		this.projectByProjectReportFilesId = projectByProjectReportFilesId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectMiscFilesId", column = @Column(name = "project_misc_files_id")),
			@AttributeOverride(name = "documentId", column = @Column(name = "document_id")),
			@AttributeOverride(name = "projectProposalFilesId", column = @Column(name = "project_proposal_files_id")),
			@AttributeOverride(name = "projectReportFilesId", column = @Column(name = "project_report_files_id")) })
	public ProjectDocumentId getId() {
		return this.id;
	}

	public void setId(ProjectDocumentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_proposal_files_id", insertable = false, updatable = false)
	public Project getProjectByProjectProposalFilesId() {
		return this.projectByProjectProposalFilesId;
	}

	public void setProjectByProjectProposalFilesId(Project projectByProjectProposalFilesId) {
		this.projectByProjectProposalFilesId = projectByProjectProposalFilesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_misc_files_id", insertable = false, updatable = false)
	public Project getProjectByProjectMiscFilesId() {
		return this.projectByProjectMiscFilesId;
	}

	public void setProjectByProjectMiscFilesId(Project projectByProjectMiscFilesId) {
		this.projectByProjectMiscFilesId = projectByProjectMiscFilesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_id", insertable = false, updatable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_report_files_id", insertable = false, updatable = false)
	public Project getProjectByProjectReportFilesId() {
		return this.projectByProjectReportFilesId;
	}

	public void setProjectByProjectReportFilesId(Project projectByProjectReportFilesId) {
		this.projectByProjectReportFilesId = projectByProjectReportFilesId;
	}

}
