package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectDataLink generated by hbm2java
 */
@Entity
@Table(name = "project_data_link", schema = "public")
public class ProjectDataLink implements java.io.Serializable {

	private ProjectDataLinkId id;
	private DataLink dataLink;

	public ProjectDataLink() {
	}

	public ProjectDataLink(ProjectDataLinkId id) {
		this.id = id;
	}

	public ProjectDataLink(ProjectDataLinkId id, DataLink dataLink) {
		this.id = id;
		this.dataLink = dataLink;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectDataLinksId", column = @Column(name = "project_data_links_id")),
			@AttributeOverride(name = "dataLinkId", column = @Column(name = "data_link_id")),
			@AttributeOverride(name = "dataLinksIdx", column = @Column(name = "data_links_idx")) })
	public ProjectDataLinkId getId() {
		return this.id;
	}

	public void setId(ProjectDataLinkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "data_link_id", insertable = false, updatable = false)
	public DataLink getDataLink() {
		return this.dataLink;
	}

	public void setDataLink(DataLink dataLink) {
		this.dataLink = dataLink;
	}

}
