package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectLocationId generated by hbm2java
 */
@Embeddable
public class ProjectLocationId implements java.io.Serializable {

	private Long projectLocationsId;
	private Long locationId;
	private Integer locationsIdx;

	public ProjectLocationId() {
	}

	public ProjectLocationId(Long projectLocationsId, Long locationId, Integer locationsIdx) {
		this.projectLocationsId = projectLocationsId;
		this.locationId = locationId;
		this.locationsIdx = locationsIdx;
	}

	@Column(name = "project_locations_id")
	public Long getProjectLocationsId() {
		return this.projectLocationsId;
	}

	public void setProjectLocationsId(Long projectLocationsId) {
		this.projectLocationsId = projectLocationsId;
	}

	@Column(name = "location_id")
	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	@Column(name = "locations_idx")
	public Integer getLocationsIdx() {
		return this.locationsIdx;
	}

	public void setLocationsIdx(Integer locationsIdx) {
		this.locationsIdx = locationsIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectLocationId))
			return false;
		ProjectLocationId castOther = (ProjectLocationId) other;

		return ((this.getProjectLocationsId() == castOther.getProjectLocationsId())
				|| (this.getProjectLocationsId() != null && castOther.getProjectLocationsId() != null
						&& this.getProjectLocationsId().equals(castOther.getProjectLocationsId())))
				&& ((this.getLocationId() == castOther.getLocationId()) || (this.getLocationId() != null
						&& castOther.getLocationId() != null && this.getLocationId().equals(castOther.getLocationId())))
				&& ((this.getLocationsIdx() == castOther.getLocationsIdx())
						|| (this.getLocationsIdx() != null && castOther.getLocationsIdx() != null
								&& this.getLocationsIdx().equals(castOther.getLocationsIdx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjectLocationsId() == null ? 0 : this.getProjectLocationsId().hashCode());
		result = 37 * result + (getLocationId() == null ? 0 : this.getLocationId().hashCode());
		result = 37 * result + (getLocationsIdx() == null ? 0 : this.getLocationsIdx().hashCode());
		return result;
	}

}
