package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", schema = "public")
public class Rating implements java.io.Serializable {

	private long id;
	private long version;
	private Date dateCreated;
	private Date lastUpdated;
	private String raterClass;
	private long raterId;
	private double stars;
	private Set ratingLinks = new HashSet(0);

	public Rating() {
	}

	public Rating(long id, Date dateCreated, Date lastUpdated, String raterClass, long raterId, double stars) {
		this.id = id;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.raterClass = raterClass;
		this.raterId = raterId;
		this.stars = stars;
	}

	public Rating(long id, Date dateCreated, Date lastUpdated, String raterClass, long raterId, double stars,
			Set ratingLinks) {
		this.id = id;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.raterClass = raterClass;
		this.raterId = raterId;
		this.stars = stars;
		this.ratingLinks = ratingLinks;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 29)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 29)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "rater_class", nullable = false)
	public String getRaterClass() {
		return this.raterClass;
	}

	public void setRaterClass(String raterClass) {
		this.raterClass = raterClass;
	}

	@Column(name = "rater_id", nullable = false)
	public long getRaterId() {
		return this.raterId;
	}

	public void setRaterId(long raterId) {
		this.raterId = raterId;
	}

	@Column(name = "stars", nullable = false, precision = 17, scale = 17)
	public double getStars() {
		return this.stars;
	}

	public void setStars(double stars) {
		this.stars = stars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rating")
	public Set getRatingLinks() {
		return this.ratingLinks;
	}

	public void setRatingLinks(Set ratingLinks) {
		this.ratingLinks = ratingLinks;
	}

}
