package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RatingLink generated by hbm2java
 */
@Entity
@Table(name = "rating_link", schema = "public")
public class RatingLink implements java.io.Serializable {

	private long id;
	private long version;
	private Rating rating;
	private long ratingRef;
	private String type;

	public RatingLink() {
	}

	public RatingLink(long id, Rating rating, long ratingRef, String type) {
		this.id = id;
		this.rating = rating;
		this.ratingRef = ratingRef;
		this.type = type;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rating_id", nullable = false)
	public Rating getRating() {
		return this.rating;
	}

	public void setRating(Rating rating) {
		this.rating = rating;
	}

	@Column(name = "rating_ref", nullable = false)
	public long getRatingRef() {
		return this.ratingRef;
	}

	public void setRatingRef(long ratingRef) {
		this.ratingRef = ratingRef;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
