package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Reference generated by hbm2java
 */
@Entity
@Table(name = "reference", schema = "public")
public class Reference implements java.io.Serializable {

	private long id;
	private long version;
	private SpeciesField speciesField;
	private String title;
	private String url;

	public Reference() {
	}

	public Reference(long id, SpeciesField speciesField) {
		this.id = id;
		this.speciesField = speciesField;
	}

	public Reference(long id, SpeciesField speciesField, String title, String url) {
		this.id = id;
		this.speciesField = speciesField;
		this.title = title;
		this.url = url;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_field_id", nullable = false)
	public SpeciesField getSpeciesField() {
		return this.speciesField;
	}

	public void setSpeciesField(SpeciesField speciesField) {
		this.speciesField = speciesField;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
