package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistrationCode generated by hbm2java
 */
@Entity
@Table(name = "registration_code", schema = "public")
public class RegistrationCode implements java.io.Serializable {

	private long id;
	private Date dateCreated;
	private String token;
	private String username;
	private String class_;
	private String action;
	private String controller;

	public RegistrationCode() {
	}

	public RegistrationCode(long id, Date dateCreated, String token, String username) {
		this.id = id;
		this.dateCreated = dateCreated;
		this.token = token;
		this.username = username;
	}

	public RegistrationCode(long id, Date dateCreated, String token, String username, String class_, String action,
			String controller) {
		this.id = id;
		this.dateCreated = dateCreated;
		this.token = token;
		this.username = username;
		this.class_ = class_;
		this.action = action;
		this.controller = controller;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 29)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "token", nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "class")
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "action")
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "controller")
	public String getController() {
		return this.controller;
	}

	public void setController(String controller) {
		this.controller = controller;
	}

}
