package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ResourceLicenseId generated by hbm2java
 */
@Embeddable
public class ResourceLicenseId implements java.io.Serializable {

	private Long resourceLicensesId;
	private Long licenseId;

	public ResourceLicenseId() {
	}

	public ResourceLicenseId(Long resourceLicensesId, Long licenseId) {
		this.resourceLicensesId = resourceLicensesId;
		this.licenseId = licenseId;
	}

	@Column(name = "resource_licenses_id")
	public Long getResourceLicensesId() {
		return this.resourceLicensesId;
	}

	public void setResourceLicensesId(Long resourceLicensesId) {
		this.resourceLicensesId = resourceLicensesId;
	}

	@Column(name = "license_id")
	public Long getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(Long licenseId) {
		this.licenseId = licenseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourceLicenseId))
			return false;
		ResourceLicenseId castOther = (ResourceLicenseId) other;

		return ((this.getResourceLicensesId() == castOther.getResourceLicensesId())
				|| (this.getResourceLicensesId() != null && castOther.getResourceLicensesId() != null
						&& this.getResourceLicensesId().equals(castOther.getResourceLicensesId())))
				&& ((this.getLicenseId() == castOther.getLicenseId()) || (this.getLicenseId() != null
						&& castOther.getLicenseId() != null && this.getLicenseId().equals(castOther.getLicenseId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getResourceLicensesId() == null ? 0 : this.getResourceLicensesId().hashCode());
		result = 37 * result + (getLicenseId() == null ? 0 : this.getLicenseId().hashCode());
		return result;
	}

}
