package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceContributor generated by hbm2java
 */
@Entity
@Table(name = "resource_contributor", schema = "public")
public class ResourceContributor implements java.io.Serializable {

	private ResourceContributorId id;
	private Resource resourceByResourceAttributorsId;
	private Resource resourceByResourceContributorsId;
	private Contributor contributor;

	public ResourceContributor() {
	}

	public ResourceContributor(ResourceContributorId id) {
		this.id = id;
	}

	public ResourceContributor(ResourceContributorId id, Resource resourceByResourceAttributorsId,
			Resource resourceByResourceContributorsId, Contributor contributor) {
		this.id = id;
		this.resourceByResourceAttributorsId = resourceByResourceAttributorsId;
		this.resourceByResourceContributorsId = resourceByResourceContributorsId;
		this.contributor = contributor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resourceAttributorsId", column = @Column(name = "resource_attributors_id")),
			@AttributeOverride(name = "contributorId", column = @Column(name = "contributor_id")),
			@AttributeOverride(name = "resourceContributorsId", column = @Column(name = "resource_contributors_id")) })
	public ResourceContributorId getId() {
		return this.id;
	}

	public void setId(ResourceContributorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_attributors_id", insertable = false, updatable = false)
	public Resource getResourceByResourceAttributorsId() {
		return this.resourceByResourceAttributorsId;
	}

	public void setResourceByResourceAttributorsId(Resource resourceByResourceAttributorsId) {
		this.resourceByResourceAttributorsId = resourceByResourceAttributorsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_contributors_id", insertable = false, updatable = false)
	public Resource getResourceByResourceContributorsId() {
		return this.resourceByResourceContributorsId;
	}

	public void setResourceByResourceContributorsId(Resource resourceByResourceContributorsId) {
		this.resourceByResourceContributorsId = resourceByResourceContributorsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contributor_id", insertable = false, updatable = false)
	public Contributor getContributor() {
		return this.contributor;
	}

	public void setContributor(Contributor contributor) {
		this.contributor = contributor;
	}

}
