package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", schema = "public")
public class Resource implements java.io.Serializable {

	private long id;
	private long version;
	private Language language;
	private License license;
	private Suser suser;
	private String description;
	private String fileName;
	private String mimeType;
	private String type;
	private String url;
	private Integer rating;
	private Date uploadTime;
	private String context;
	private String accessRights;
	private String annotations;
	private Long gbifid;
	private Set observations = new HashSet(0);
	private Set speciesResources = new HashSet(0);
	private Set commentResources = new HashSet(0);
	private Set resourceLicenses = new HashSet(0);
	private Set observationReprImages = new HashSet(0);
	private Set speciesFields = new HashSet(0);
	private Set resourceContributorsForResourceContributorsId = new HashSet(0);
	private Set usersResources = new HashSet(0);
	private Set observations_1 = new HashSet(0);
	private Set resourceContributorsForResourceAttributorsId = new HashSet(0);
	private Set specieses = new HashSet(0);

	public Resource() {
	}

	public Resource(long id, Language language, License license, String fileName, String type) {
		this.id = id;
		this.language = language;
		this.license = license;
		this.fileName = fileName;
		this.type = type;
	}

	public Resource(long id, Language language, License license, Suser suser, String description, String fileName,
			String mimeType, String type, String url, Integer rating, Date uploadTime, String context,
			String accessRights, String annotations, Long gbifid, Set observations, Set speciesResources,
			Set commentResources, Set resourceLicenses, Set observationReprImages, Set speciesFields,
			Set resourceContributorsForResourceContributorsId, Set usersResources, Set observations_1,
			Set resourceContributorsForResourceAttributorsId, Set specieses) {
		this.id = id;
		this.language = language;
		this.license = license;
		this.suser = suser;
		this.description = description;
		this.fileName = fileName;
		this.mimeType = mimeType;
		this.type = type;
		this.url = url;
		this.rating = rating;
		this.uploadTime = uploadTime;
		this.context = context;
		this.accessRights = accessRights;
		this.annotations = annotations;
		this.gbifid = gbifid;
		this.observations = observations;
		this.speciesResources = speciesResources;
		this.commentResources = commentResources;
		this.resourceLicenses = resourceLicenses;
		this.observationReprImages = observationReprImages;
		this.speciesFields = speciesFields;
		this.resourceContributorsForResourceContributorsId = resourceContributorsForResourceContributorsId;
		this.usersResources = usersResources;
		this.observations_1 = observations_1;
		this.resourceContributorsForResourceAttributorsId = resourceContributorsForResourceAttributorsId;
		this.specieses = specieses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "license_id", nullable = false)
	public License getLicense() {
		return this.license;
	}

	public void setLicense(License license) {
		this.license = license;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uploader_id")
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "file_name", nullable = false)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "mime_type")
	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upload_time", length = 29)
	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	@Column(name = "context")
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "access_rights", length = 2055)
	public String getAccessRights() {
		return this.accessRights;
	}

	public void setAccessRights(String accessRights) {
		this.accessRights = accessRights;
	}

	@Column(name = "annotations")
	public String getAnnotations() {
		return this.annotations;
	}

	public void setAnnotations(String annotations) {
		this.annotations = annotations;
	}

	@Column(name = "gbifid")
	public Long getGbifid() {
		return this.gbifid;
	}

	public void setGbifid(Long gbifid) {
		this.gbifid = gbifid;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "observation_resource", schema = "public", joinColumns = {
			@JoinColumn(name = "resource_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "observation_id", nullable = false, updatable = false) })
	public Set getObservations() {
		return this.observations;
	}

	public void setObservations(Set observations) {
		this.observations = observations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getSpeciesResources() {
		return this.speciesResources;
	}

	public void setSpeciesResources(Set speciesResources) {
		this.speciesResources = speciesResources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getCommentResources() {
		return this.commentResources;
	}

	public void setCommentResources(Set commentResources) {
		this.commentResources = commentResources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getResourceLicenses() {
		return this.resourceLicenses;
	}

	public void setResourceLicenses(Set resourceLicenses) {
		this.resourceLicenses = resourceLicenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getObservationReprImages() {
		return this.observationReprImages;
	}

	public void setObservationReprImages(Set observationReprImages) {
		this.observationReprImages = observationReprImages;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "species_field_resources", schema = "public", joinColumns = {
			@JoinColumn(name = "resource_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "species_field_id", nullable = false, updatable = false) })
	public Set getSpeciesFields() {
		return this.speciesFields;
	}

	public void setSpeciesFields(Set speciesFields) {
		this.speciesFields = speciesFields;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByResourceContributorsId")
	public Set getResourceContributorsForResourceContributorsId() {
		return this.resourceContributorsForResourceContributorsId;
	}

	public void setResourceContributorsForResourceContributorsId(Set resourceContributorsForResourceContributorsId) {
		this.resourceContributorsForResourceContributorsId = resourceContributorsForResourceContributorsId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getUsersResources() {
		return this.usersResources;
	}

	public void setUsersResources(Set usersResources) {
		this.usersResources = usersResources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getObservations_1() {
		return this.observations_1;
	}

	public void setObservations_1(Set observations_1) {
		this.observations_1 = observations_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByResourceAttributorsId")
	public Set getResourceContributorsForResourceAttributorsId() {
		return this.resourceContributorsForResourceAttributorsId;
	}

	public void setResourceContributorsForResourceAttributorsId(Set resourceContributorsForResourceAttributorsId) {
		this.resourceContributorsForResourceAttributorsId = resourceContributorsForResourceAttributorsId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set getSpecieses() {
		return this.specieses;
	}

	public void setSpecieses(Set specieses) {
		this.specieses = specieses;
	}

}
