package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * ResourceRedirect generated by hbm2java
 */
@Entity
@Table(name = "resource_redirect", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = { "target_id",
		"target_type", "source_type", "source_id" }))
public class ResourceRedirect implements java.io.Serializable {

	private long id;
	private long version;
	private long sourceId;
	private String sourceType;
	private long targetId;
	private String targetType;

	public ResourceRedirect() {
	}

	public ResourceRedirect(long id, long sourceId, String sourceType, long targetId, String targetType) {
		this.id = id;
		this.sourceId = sourceId;
		this.sourceType = sourceType;
		this.targetId = targetId;
		this.targetType = targetType;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "source_id", nullable = false)
	public long getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(long sourceId) {
		this.sourceId = sourceId;
	}

	@Column(name = "source_type", nullable = false)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "target_id", nullable = false)
	public long getTargetId() {
		return this.targetId;
	}

	public void setTargetId(long targetId) {
		this.targetId = targetId;
	}

	@Column(name = "target_type", nullable = false)
	public String getTargetType() {
		return this.targetType;
	}

	public void setTargetType(String targetType) {
		this.targetType = targetType;
	}

}
