package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SpeciesResourceBak generated by hbm2java
 */
@Entity
@Table(name = "species_resource_bak", schema = "public")
public class SpeciesResourceBak implements java.io.Serializable {

	private SpeciesResourceBakId id;

	public SpeciesResourceBak() {
	}

	public SpeciesResourceBak(SpeciesResourceBakId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "speciesResourcesId", column = @Column(name = "species_resources_id")),
			@AttributeOverride(name = "resourceId", column = @Column(name = "resource_id")) })
	public SpeciesResourceBakId getId() {
		return this.id;
	}

	public void setId(SpeciesResourceBakId id) {
		this.id = id;
	}

}
