package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpeciesFieldContributorId generated by hbm2java
 */
@Embeddable
public class SpeciesFieldContributorId implements java.io.Serializable {

	private Long speciesFieldAttributorsId;
	private Long contributorId;
	private Integer attributorsIdx;

	public SpeciesFieldContributorId() {
	}

	public SpeciesFieldContributorId(Long speciesFieldAttributorsId, Long contributorId, Integer attributorsIdx) {
		this.speciesFieldAttributorsId = speciesFieldAttributorsId;
		this.contributorId = contributorId;
		this.attributorsIdx = attributorsIdx;
	}

	@Column(name = "species_field_attributors_id")
	public Long getSpeciesFieldAttributorsId() {
		return this.speciesFieldAttributorsId;
	}

	public void setSpeciesFieldAttributorsId(Long speciesFieldAttributorsId) {
		this.speciesFieldAttributorsId = speciesFieldAttributorsId;
	}

	@Column(name = "contributor_id")
	public Long getContributorId() {
		return this.contributorId;
	}

	public void setContributorId(Long contributorId) {
		this.contributorId = contributorId;
	}

	@Column(name = "attributors_idx")
	public Integer getAttributorsIdx() {
		return this.attributorsIdx;
	}

	public void setAttributorsIdx(Integer attributorsIdx) {
		this.attributorsIdx = attributorsIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpeciesFieldContributorId))
			return false;
		SpeciesFieldContributorId castOther = (SpeciesFieldContributorId) other;

		return ((this.getSpeciesFieldAttributorsId() == castOther.getSpeciesFieldAttributorsId())
				|| (this.getSpeciesFieldAttributorsId() != null && castOther.getSpeciesFieldAttributorsId() != null
						&& this.getSpeciesFieldAttributorsId().equals(castOther.getSpeciesFieldAttributorsId())))
				&& ((this.getContributorId() == castOther.getContributorId())
						|| (this.getContributorId() != null && castOther.getContributorId() != null
								&& this.getContributorId().equals(castOther.getContributorId())))
				&& ((this.getAttributorsIdx() == castOther.getAttributorsIdx())
						|| (this.getAttributorsIdx() != null && castOther.getAttributorsIdx() != null
								&& this.getAttributorsIdx().equals(castOther.getAttributorsIdx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSpeciesFieldAttributorsId() == null ? 0 : this.getSpeciesFieldAttributorsId().hashCode());
		result = 37 * result + (getContributorId() == null ? 0 : this.getContributorId().hashCode());
		result = 37 * result + (getAttributorsIdx() == null ? 0 : this.getAttributorsIdx().hashCode());
		return result;
	}

}
