package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpeciesFieldAudienceTypesId generated by hbm2java
 */
@Embeddable
public class SpeciesFieldAudienceTypesId implements java.io.Serializable {

	private Long speciesFieldId;
	private String speciesField$audienceType;

	public SpeciesFieldAudienceTypesId() {
	}

	public SpeciesFieldAudienceTypesId(Long speciesFieldId, String speciesField$audienceType) {
		this.speciesFieldId = speciesFieldId;
		this.speciesField$audienceType = speciesField$audienceType;
	}

	@Column(name = "species_field_id")
	public Long getSpeciesFieldId() {
		return this.speciesFieldId;
	}

	public void setSpeciesFieldId(Long speciesFieldId) {
		this.speciesFieldId = speciesFieldId;
	}

	@Column(name = "species_field$audience_type")
	public String getSpeciesField$audienceType() {
		return this.speciesField$audienceType;
	}

	public void setSpeciesField$audienceType(String speciesField$audienceType) {
		this.speciesField$audienceType = speciesField$audienceType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpeciesFieldAudienceTypesId))
			return false;
		SpeciesFieldAudienceTypesId castOther = (SpeciesFieldAudienceTypesId) other;

		return ((this.getSpeciesFieldId() == castOther.getSpeciesFieldId())
				|| (this.getSpeciesFieldId() != null && castOther.getSpeciesFieldId() != null
						&& this.getSpeciesFieldId().equals(castOther.getSpeciesFieldId())))
				&& ((this.getSpeciesField$audienceType() == castOther.getSpeciesField$audienceType())
						|| (this.getSpeciesField$audienceType() != null
								&& castOther.getSpeciesField$audienceType() != null
								&& this.getSpeciesField$audienceType()
										.equals(castOther.getSpeciesField$audienceType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSpeciesFieldId() == null ? 0 : this.getSpeciesFieldId().hashCode());
		result = 37 * result
				+ (getSpeciesField$audienceType() == null ? 0 : this.getSpeciesField$audienceType().hashCode());
		return result;
	}

}
