package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpeciesResource generated by hbm2java
 */
@Entity
@Table(name = "species_resource", schema = "public")
public class SpeciesResource implements java.io.Serializable {

	private SpeciesResourceId id;
	private Resource resource;
	private Species species;

	public SpeciesResource() {
	}

	public SpeciesResource(SpeciesResourceId id) {
		this.id = id;
	}

	public SpeciesResource(SpeciesResourceId id, Resource resource, Species species) {
		this.id = id;
		this.resource = resource;
		this.species = species;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "speciesResourcesId", column = @Column(name = "species_resources_id")),
			@AttributeOverride(name = "resourceId", column = @Column(name = "resource_id")) })
	public SpeciesResourceId getId() {
		return this.id;
	}

	public void setId(SpeciesResourceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_id", insertable = false, updatable = false)
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_resources_id", insertable = false, updatable = false)
	public Species getSpecies() {
		return this.species;
	}

	public void setSpecies(Species species) {
		this.species = species;
	}

}
