package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpeciesFieldContributor generated by hbm2java
 */
@Entity
@Table(name = "species_field_contributor", schema = "public")
public class SpeciesFieldContributor implements java.io.Serializable {

	private SpeciesFieldContributorId id;
	private SpeciesField speciesField;
	private Contributor contributor;

	public SpeciesFieldContributor() {
	}

	public SpeciesFieldContributor(SpeciesFieldContributorId id) {
		this.id = id;
	}

	public SpeciesFieldContributor(SpeciesFieldContributorId id, SpeciesField speciesField, Contributor contributor) {
		this.id = id;
		this.speciesField = speciesField;
		this.contributor = contributor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "speciesFieldAttributorsId", column = @Column(name = "species_field_attributors_id")),
			@AttributeOverride(name = "contributorId", column = @Column(name = "contributor_id")),
			@AttributeOverride(name = "attributorsIdx", column = @Column(name = "attributors_idx")) })
	public SpeciesFieldContributorId getId() {
		return this.id;
	}

	public void setId(SpeciesFieldContributorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_field_attributors_id", insertable = false, updatable = false)
	public SpeciesField getSpeciesField() {
		return this.speciesField;
	}

	public void setSpeciesField(SpeciesField speciesField) {
		this.speciesField = speciesField;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contributor_id", insertable = false, updatable = false)
	public Contributor getContributor() {
		return this.contributor;
	}

	public void setContributor(Contributor contributor) {
		this.contributor = contributor;
	}

}
