package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpeciesFieldLicense generated by hbm2java
 */
@Entity
@Table(name = "species_field_license", schema = "public")
public class SpeciesFieldLicense implements java.io.Serializable {

	private SpeciesFieldLicenseId id;
	private License license;
	private SpeciesField speciesField;

	public SpeciesFieldLicense() {
	}

	public SpeciesFieldLicense(SpeciesFieldLicenseId id) {
		this.id = id;
	}

	public SpeciesFieldLicense(SpeciesFieldLicenseId id, License license, SpeciesField speciesField) {
		this.id = id;
		this.license = license;
		this.speciesField = speciesField;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "speciesFieldLicensesId", column = @Column(name = "species_field_licenses_id")),
			@AttributeOverride(name = "licenseId", column = @Column(name = "license_id")) })
	public SpeciesFieldLicenseId getId() {
		return this.id;
	}

	public void setId(SpeciesFieldLicenseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "license_id", insertable = false, updatable = false)
	public License getLicense() {
		return this.license;
	}

	public void setLicense(License license) {
		this.license = license;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_field_licenses_id", insertable = false, updatable = false)
	public SpeciesField getSpeciesField() {
		return this.speciesField;
	}

	public void setSpeciesField(SpeciesField speciesField) {
		this.speciesField = speciesField;
	}

}
