package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpeciesFieldAudienceTypes generated by hbm2java
 */
@Entity
@Table(name = "species_field_audience_types", schema = "public")
public class SpeciesFieldAudienceTypes implements java.io.Serializable {

	private SpeciesFieldAudienceTypesId id;
	private SpeciesField speciesField;

	public SpeciesFieldAudienceTypes() {
	}

	public SpeciesFieldAudienceTypes(SpeciesFieldAudienceTypesId id) {
		this.id = id;
	}

	public SpeciesFieldAudienceTypes(SpeciesFieldAudienceTypesId id, SpeciesField speciesField) {
		this.id = id;
		this.speciesField = speciesField;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "speciesFieldId", column = @Column(name = "species_field_id")),
			@AttributeOverride(name = "speciesField$audienceType", column = @Column(name = "species_field$audience_type")) })
	public SpeciesFieldAudienceTypesId getId() {
		return this.id;
	}

	public void setId(SpeciesFieldAudienceTypesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_field_id", insertable = false, updatable = false)
	public SpeciesField getSpeciesField() {
		return this.speciesField;
	}

	public void setSpeciesField(SpeciesField speciesField) {
		this.speciesField = speciesField;
	}

}
