package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpeciesResourceId generated by hbm2java
 */
@Embeddable
public class SpeciesResourceId implements java.io.Serializable {

	private Long speciesResourcesId;
	private Long resourceId;

	public SpeciesResourceId() {
	}

	public SpeciesResourceId(Long speciesResourcesId, Long resourceId) {
		this.speciesResourcesId = speciesResourcesId;
		this.resourceId = resourceId;
	}

	@Column(name = "species_resources_id")
	public Long getSpeciesResourcesId() {
		return this.speciesResourcesId;
	}

	public void setSpeciesResourcesId(Long speciesResourcesId) {
		this.speciesResourcesId = speciesResourcesId;
	}

	@Column(name = "resource_id")
	public Long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpeciesResourceId))
			return false;
		SpeciesResourceId castOther = (SpeciesResourceId) other;

		return ((this.getSpeciesResourcesId() == castOther.getSpeciesResourcesId())
				|| (this.getSpeciesResourcesId() != null && castOther.getSpeciesResourcesId() != null
						&& this.getSpeciesResourcesId().equals(castOther.getSpeciesResourcesId())))
				&& ((this.getResourceId() == castOther.getResourceId())
						|| (this.getResourceId() != null && castOther.getResourceId() != null
								&& this.getResourceId().equals(castOther.getResourceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSpeciesResourcesId() == null ? 0 : this.getSpeciesResourcesId().hashCode());
		result = 37 * result + (getResourceId() == null ? 0 : this.getResourceId().hashCode());
		return result;
	}

}
