package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * StrategicDirection generated by hbm2java
 */
@Entity
@Table(name = "strategic_direction", schema = "public")
public class StrategicDirection implements java.io.Serializable {

	private long id;
	private long version;
	private String strategy;
	private String title;
	private Set projects = new HashSet(0);

	public StrategicDirection() {
	}

	public StrategicDirection(long id, String strategy, String title) {
		this.id = id;
		this.strategy = strategy;
		this.title = title;
	}

	public StrategicDirection(long id, String strategy, String title, Set projects) {
		this.id = id;
		this.strategy = strategy;
		this.title = title;
		this.projects = projects;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "strategy", nullable = false)
	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "strategicDirection")
	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

}
