package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SuserUserGroupId generated by hbm2java
 */
@Embeddable
public class SuserUserGroupId implements java.io.Serializable {

	private Long suserGroupsId;
	private Long userGroupId;

	public SuserUserGroupId() {
	}

	public SuserUserGroupId(Long suserGroupsId, Long userGroupId) {
		this.suserGroupsId = suserGroupsId;
		this.userGroupId = userGroupId;
	}

	@Column(name = "suser_groups_id")
	public Long getSuserGroupsId() {
		return this.suserGroupsId;
	}

	public void setSuserGroupsId(Long suserGroupsId) {
		this.suserGroupsId = suserGroupsId;
	}

	@Column(name = "user_group_id")
	public Long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(Long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SuserUserGroupId))
			return false;
		SuserUserGroupId castOther = (SuserUserGroupId) other;

		return ((this.getSuserGroupsId() == castOther.getSuserGroupsId())
				|| (this.getSuserGroupsId() != null && castOther.getSuserGroupsId() != null
						&& this.getSuserGroupsId().equals(castOther.getSuserGroupsId())))
				&& ((this.getUserGroupId() == castOther.getUserGroupId())
						|| (this.getUserGroupId() != null && castOther.getUserGroupId() != null
								&& this.getUserGroupId().equals(castOther.getUserGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSuserGroupsId() == null ? 0 : this.getSuserGroupsId().hashCode());
		result = 37 * result + (getUserGroupId() == null ? 0 : this.getUserGroupId().hashCode());
		return result;
	}

}
