package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SuserSpeciesGroupId generated by hbm2java
 */
@Embeddable
public class SuserSpeciesGroupId implements java.io.Serializable {

	private Long suserSpeciesGroupsId;
	private Long speciesGroupId;

	public SuserSpeciesGroupId() {
	}

	public SuserSpeciesGroupId(Long suserSpeciesGroupsId, Long speciesGroupId) {
		this.suserSpeciesGroupsId = suserSpeciesGroupsId;
		this.speciesGroupId = speciesGroupId;
	}

	@Column(name = "suser_species_groups_id")
	public Long getSuserSpeciesGroupsId() {
		return this.suserSpeciesGroupsId;
	}

	public void setSuserSpeciesGroupsId(Long suserSpeciesGroupsId) {
		this.suserSpeciesGroupsId = suserSpeciesGroupsId;
	}

	@Column(name = "species_group_id")
	public Long getSpeciesGroupId() {
		return this.speciesGroupId;
	}

	public void setSpeciesGroupId(Long speciesGroupId) {
		this.speciesGroupId = speciesGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SuserSpeciesGroupId))
			return false;
		SuserSpeciesGroupId castOther = (SuserSpeciesGroupId) other;

		return ((this.getSuserSpeciesGroupsId() == castOther.getSuserSpeciesGroupsId())
				|| (this.getSuserSpeciesGroupsId() != null && castOther.getSuserSpeciesGroupsId() != null
						&& this.getSuserSpeciesGroupsId().equals(castOther.getSuserSpeciesGroupsId())))
				&& ((this.getSpeciesGroupId() == castOther.getSpeciesGroupId())
						|| (this.getSpeciesGroupId() != null && castOther.getSpeciesGroupId() != null
								&& this.getSpeciesGroupId().equals(castOther.getSpeciesGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSuserSpeciesGroupsId() == null ? 0 : this.getSuserSpeciesGroupsId().hashCode());
		result = 37 * result + (getSpeciesGroupId() == null ? 0 : this.getSpeciesGroupId().hashCode());
		return result;
	}

}
