package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SuserUserGroup generated by hbm2java
 */
@Entity
@Table(name = "suser_user_group", schema = "public")
public class SuserUserGroup implements java.io.Serializable {

	private SuserUserGroupId id;
	private UserGroup userGroup;
	private Suser suser;

	public SuserUserGroup() {
	}

	public SuserUserGroup(SuserUserGroupId id) {
		this.id = id;
	}

	public SuserUserGroup(SuserUserGroupId id, UserGroup userGroup, Suser suser) {
		this.id = id;
		this.userGroup = userGroup;
		this.suser = suser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "suserGroupsId", column = @Column(name = "suser_groups_id")),
			@AttributeOverride(name = "userGroupId", column = @Column(name = "user_group_id")) })
	public SuserUserGroupId getId() {
		return this.id;
	}

	public void setId(SuserUserGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_group_id", insertable = false, updatable = false)
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suser_groups_id", insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

}
