package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SuserSpeciesGroup generated by hbm2java
 */
@Entity
@Table(name = "suser_species_group", schema = "public")
public class SuserSpeciesGroup implements java.io.Serializable {

	private SuserSpeciesGroupId id;
	private Suser suser;
	private SpeciesGroup speciesGroup;

	public SuserSpeciesGroup() {
	}

	public SuserSpeciesGroup(SuserSpeciesGroupId id) {
		this.id = id;
	}

	public SuserSpeciesGroup(SuserSpeciesGroupId id, Suser suser, SpeciesGroup speciesGroup) {
		this.id = id;
		this.suser = suser;
		this.speciesGroup = speciesGroup;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "suserSpeciesGroupsId", column = @Column(name = "suser_species_groups_id")),
			@AttributeOverride(name = "speciesGroupId", column = @Column(name = "species_group_id")) })
	public SuserSpeciesGroupId getId() {
		return this.id;
	}

	public void setId(SuserSpeciesGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suser_species_groups_id", insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_group_id", insertable = false, updatable = false)
	public SpeciesGroup getSpeciesGroup() {
		return this.speciesGroup;
	}

	public void setSpeciesGroup(SpeciesGroup speciesGroup) {
		this.speciesGroup = speciesGroup;
	}

}
