package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SuserObservations generated by hbm2java
 */
@Entity
@Table(name = "suser_observations", schema = "public")
public class SuserObservations implements java.io.Serializable {

	private SuserObservationsId id;
	private Checklists checklists;
	private Suser suser;

	public SuserObservations() {
	}

	public SuserObservations(SuserObservationsId id) {
		this.id = id;
	}

	public SuserObservations(SuserObservationsId id, Checklists checklists, Suser suser) {
		this.id = id;
		this.checklists = checklists;
		this.suser = suser;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "checklistsId", column = @Column(name = "checklists_id")),
			@AttributeOverride(name = "observationsId", column = @Column(name = "observations_id")) })
	public SuserObservationsId getId() {
		return this.id;
	}

	public void setId(SuserObservationsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "checklists_id", insertable = false, updatable = false)
	public Checklists getChecklists() {
		return this.checklists;
	}

	public void setChecklists(Checklists checklists) {
		this.checklists = checklists;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "observations_id", insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

}
