package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SynonymsSuserId generated by hbm2java
 */
@Embeddable
public class SynonymsSuserId implements java.io.Serializable {

	private Long synonymsContributorsId;
	private Long suserId;
	private Integer contributorsIdx;
	private Long synonymsCuratorsId;
	private Integer curatorsIdx;

	public SynonymsSuserId() {
	}

	public SynonymsSuserId(Long synonymsContributorsId, Long suserId, Integer contributorsIdx, Long synonymsCuratorsId,
			Integer curatorsIdx) {
		this.synonymsContributorsId = synonymsContributorsId;
		this.suserId = suserId;
		this.contributorsIdx = contributorsIdx;
		this.synonymsCuratorsId = synonymsCuratorsId;
		this.curatorsIdx = curatorsIdx;
	}

	@Column(name = "synonyms_contributors_id")
	public Long getSynonymsContributorsId() {
		return this.synonymsContributorsId;
	}

	public void setSynonymsContributorsId(Long synonymsContributorsId) {
		this.synonymsContributorsId = synonymsContributorsId;
	}

	@Column(name = "suser_id")
	public Long getSuserId() {
		return this.suserId;
	}

	public void setSuserId(Long suserId) {
		this.suserId = suserId;
	}

	@Column(name = "contributors_idx")
	public Integer getContributorsIdx() {
		return this.contributorsIdx;
	}

	public void setContributorsIdx(Integer contributorsIdx) {
		this.contributorsIdx = contributorsIdx;
	}

	@Column(name = "synonyms_curators_id")
	public Long getSynonymsCuratorsId() {
		return this.synonymsCuratorsId;
	}

	public void setSynonymsCuratorsId(Long synonymsCuratorsId) {
		this.synonymsCuratorsId = synonymsCuratorsId;
	}

	@Column(name = "curators_idx")
	public Integer getCuratorsIdx() {
		return this.curatorsIdx;
	}

	public void setCuratorsIdx(Integer curatorsIdx) {
		this.curatorsIdx = curatorsIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SynonymsSuserId))
			return false;
		SynonymsSuserId castOther = (SynonymsSuserId) other;

		return ((this.getSynonymsContributorsId() == castOther.getSynonymsContributorsId())
				|| (this.getSynonymsContributorsId() != null && castOther.getSynonymsContributorsId() != null
						&& this.getSynonymsContributorsId().equals(castOther.getSynonymsContributorsId())))
				&& ((this.getSuserId() == castOther.getSuserId()) || (this.getSuserId() != null
						&& castOther.getSuserId() != null && this.getSuserId().equals(castOther.getSuserId())))
				&& ((this.getContributorsIdx() == castOther.getContributorsIdx())
						|| (this.getContributorsIdx() != null && castOther.getContributorsIdx() != null
								&& this.getContributorsIdx().equals(castOther.getContributorsIdx())))
				&& ((this.getSynonymsCuratorsId() == castOther.getSynonymsCuratorsId())
						|| (this.getSynonymsCuratorsId() != null && castOther.getSynonymsCuratorsId() != null
								&& this.getSynonymsCuratorsId().equals(castOther.getSynonymsCuratorsId())))
				&& ((this.getCuratorsIdx() == castOther.getCuratorsIdx())
						|| (this.getCuratorsIdx() != null && castOther.getCuratorsIdx() != null
								&& this.getCuratorsIdx().equals(castOther.getCuratorsIdx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSynonymsContributorsId() == null ? 0 : this.getSynonymsContributorsId().hashCode());
		result = 37 * result + (getSuserId() == null ? 0 : this.getSuserId().hashCode());
		result = 37 * result + (getContributorsIdx() == null ? 0 : this.getContributorsIdx().hashCode());
		result = 37 * result + (getSynonymsCuratorsId() == null ? 0 : this.getSynonymsCuratorsId().hashCode());
		result = 37 * result + (getCuratorsIdx() == null ? 0 : this.getCuratorsIdx().hashCode());
		return result;
	}

}
