package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TagLinks generated by hbm2java
 */
@Entity
@Table(name = "tag_links", schema = "public")
public class TagLinks implements java.io.Serializable {

	private long id;
	private long version;
	private Tags tags;
	private long tagRef;
	private String type;

	public TagLinks() {
	}

	public TagLinks(long id, Tags tags, long tagRef, String type) {
		this.id = id;
		this.tags = tags;
		this.tagRef = tagRef;
		this.type = type;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag_id", nullable = false)
	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

	@Column(name = "tag_ref", nullable = false)
	public long getTagRef() {
		return this.tagRef;
	}

	public void setTagRef(long tagRef) {
		this.tagRef = tagRef;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
