package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Tags implements java.io.Serializable {

	private long id;
	private long version;
	private String name;
	private Set tagLinkses = new HashSet(0);

	public Tags() {
	}

	public Tags(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Tags(long id, String name, Set tagLinkses) {
		this.id = id;
		this.name = name;
		this.tagLinkses = tagLinkses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set getTagLinkses() {
		return this.tagLinkses;
	}

	public void setTagLinkses(Set tagLinkses) {
		this.tagLinkses = tagLinkses;
	}

}
