package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaxonomyDefinitionAuthorId generated by hbm2java
 */
@Embeddable
public class TaxonomyDefinitionAuthorId implements java.io.Serializable {

	private Long taxonomyDefinitionId;
	private String authorString;

	public TaxonomyDefinitionAuthorId() {
	}

	public TaxonomyDefinitionAuthorId(Long taxonomyDefinitionId, String authorString) {
		this.taxonomyDefinitionId = taxonomyDefinitionId;
		this.authorString = authorString;
	}

	@Column(name = "taxonomy_definition_id")
	public Long getTaxonomyDefinitionId() {
		return this.taxonomyDefinitionId;
	}

	public void setTaxonomyDefinitionId(Long taxonomyDefinitionId) {
		this.taxonomyDefinitionId = taxonomyDefinitionId;
	}

	@Column(name = "author_string")
	public String getAuthorString() {
		return this.authorString;
	}

	public void setAuthorString(String authorString) {
		this.authorString = authorString;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaxonomyDefinitionAuthorId))
			return false;
		TaxonomyDefinitionAuthorId castOther = (TaxonomyDefinitionAuthorId) other;

		return ((this.getTaxonomyDefinitionId() == castOther.getTaxonomyDefinitionId())
				|| (this.getTaxonomyDefinitionId() != null && castOther.getTaxonomyDefinitionId() != null
						&& this.getTaxonomyDefinitionId().equals(castOther.getTaxonomyDefinitionId())))
				&& ((this.getAuthorString() == castOther.getAuthorString())
						|| (this.getAuthorString() != null && castOther.getAuthorString() != null
								&& this.getAuthorString().equals(castOther.getAuthorString())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTaxonomyDefinitionId() == null ? 0 : this.getTaxonomyDefinitionId().hashCode());
		result = 37 * result + (getAuthorString() == null ? 0 : this.getAuthorString().hashCode());
		return result;
	}

}
