package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TaxonomicCoverages generated by hbm2java
 */
@Entity
@Table(name = "taxonomic_coverages", schema = "public")
public class TaxonomicCoverages implements java.io.Serializable {

	private long id;
	private long version;
	private String generalTaxonomicCoverage;

	public TaxonomicCoverages() {
	}

	public TaxonomicCoverages(long id, String generalTaxonomicCoverage) {
		this.id = id;
		this.generalTaxonomicCoverage = generalTaxonomicCoverage;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "general_taxonomic_coverage", nullable = false)
	public String getGeneralTaxonomicCoverage() {
		return this.generalTaxonomicCoverage;
	}

	public void setGeneralTaxonomicCoverage(String generalTaxonomicCoverage) {
		this.generalTaxonomicCoverage = generalTaxonomicCoverage;
	}

}
