package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaxonomyDefinitionSuser generated by hbm2java
 */
@Entity
@Table(name = "taxonomy_definition_suser", schema = "public")
public class TaxonomyDefinitionSuser implements java.io.Serializable {

	private TaxonomyDefinitionSuserId id;
	private Suser suser;
	private TaxonomyDefinition taxonomyDefinition;

	public TaxonomyDefinitionSuser() {
	}

	public TaxonomyDefinitionSuser(TaxonomyDefinitionSuserId id) {
		this.id = id;
	}

	public TaxonomyDefinitionSuser(TaxonomyDefinitionSuserId id, Suser suser, TaxonomyDefinition taxonomyDefinition) {
		this.id = id;
		this.suser = suser;
		this.taxonomyDefinition = taxonomyDefinition;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxonomyDefinitionContributorsId", column = @Column(name = "taxonomy_definition_contributors_id")),
			@AttributeOverride(name = "suserId", column = @Column(name = "suser_id")),
			@AttributeOverride(name = "contributorsIdx", column = @Column(name = "contributors_idx")),
			@AttributeOverride(name = "taxonomyDefinitionCuratorsId", column = @Column(name = "taxonomy_definition_curators_id")),
			@AttributeOverride(name = "curatorsIdx", column = @Column(name = "curators_idx")) })
	public TaxonomyDefinitionSuserId getId() {
		return this.id;
	}

	public void setId(TaxonomyDefinitionSuserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suser_id", insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxonomy_definition_contributors_id", insertable = false, updatable = false)
	public TaxonomyDefinition getTaxonomyDefinition() {
		return this.taxonomyDefinition;
	}

	public void setTaxonomyDefinition(TaxonomyDefinition taxonomyDefinition) {
		this.taxonomyDefinition = taxonomyDefinition;
	}

}
