package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaxonomyRegistrySuser generated by hbm2java
 */
@Entity
@Table(name = "taxonomy_registry_suser", schema = "public")
public class TaxonomyRegistrySuser implements java.io.Serializable {

	private TaxonomyRegistrySuserId id;
	private Suser suser;
	private TaxonomyRegistry taxonomyRegistry;

	public TaxonomyRegistrySuser() {
	}

	public TaxonomyRegistrySuser(TaxonomyRegistrySuserId id) {
		this.id = id;
	}

	public TaxonomyRegistrySuser(TaxonomyRegistrySuserId id, Suser suser, TaxonomyRegistry taxonomyRegistry) {
		this.id = id;
		this.suser = suser;
		this.taxonomyRegistry = taxonomyRegistry;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxonomyRegistryContributorsId", column = @Column(name = "taxonomy_registry_contributors_id")),
			@AttributeOverride(name = "suserId", column = @Column(name = "suser_id")),
			@AttributeOverride(name = "contributorsIdx", column = @Column(name = "contributors_idx")) })
	public TaxonomyRegistrySuserId getId() {
		return this.id;
	}

	public void setId(TaxonomyRegistrySuserId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "suser_id", insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxonomy_registry_contributors_id", insertable = false, updatable = false)
	public TaxonomyRegistry getTaxonomyRegistry() {
		return this.taxonomyRegistry;
	}

	public void setTaxonomyRegistry(TaxonomyRegistry taxonomyRegistry) {
		this.taxonomyRegistry = taxonomyRegistry;
	}

}
