package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TaxonomyRegistrySuserId generated by hbm2java
 */
@Embeddable
public class TaxonomyRegistrySuserId implements java.io.Serializable {

	private Long taxonomyRegistryContributorsId;
	private Long suserId;
	private Integer contributorsIdx;

	public TaxonomyRegistrySuserId() {
	}

	public TaxonomyRegistrySuserId(Long taxonomyRegistryContributorsId, Long suserId, Integer contributorsIdx) {
		this.taxonomyRegistryContributorsId = taxonomyRegistryContributorsId;
		this.suserId = suserId;
		this.contributorsIdx = contributorsIdx;
	}

	@Column(name = "taxonomy_registry_contributors_id")
	public Long getTaxonomyRegistryContributorsId() {
		return this.taxonomyRegistryContributorsId;
	}

	public void setTaxonomyRegistryContributorsId(Long taxonomyRegistryContributorsId) {
		this.taxonomyRegistryContributorsId = taxonomyRegistryContributorsId;
	}

	@Column(name = "suser_id")
	public Long getSuserId() {
		return this.suserId;
	}

	public void setSuserId(Long suserId) {
		this.suserId = suserId;
	}

	@Column(name = "contributors_idx")
	public Integer getContributorsIdx() {
		return this.contributorsIdx;
	}

	public void setContributorsIdx(Integer contributorsIdx) {
		this.contributorsIdx = contributorsIdx;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaxonomyRegistrySuserId))
			return false;
		TaxonomyRegistrySuserId castOther = (TaxonomyRegistrySuserId) other;

		return ((this.getTaxonomyRegistryContributorsId() == castOther.getTaxonomyRegistryContributorsId())
				|| (this.getTaxonomyRegistryContributorsId() != null
						&& castOther.getTaxonomyRegistryContributorsId() != null
						&& this.getTaxonomyRegistryContributorsId()
								.equals(castOther.getTaxonomyRegistryContributorsId())))
				&& ((this.getSuserId() == castOther.getSuserId()) || (this.getSuserId() != null
						&& castOther.getSuserId() != null && this.getSuserId().equals(castOther.getSuserId())))
				&& ((this.getContributorsIdx() == castOther.getContributorsIdx())
						|| (this.getContributorsIdx() != null && castOther.getContributorsIdx() != null
								&& this.getContributorsIdx().equals(castOther.getContributorsIdx())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTaxonomyRegistryContributorsId() == null ? 0
				: this.getTaxonomyRegistryContributorsId().hashCode());
		result = 37 * result + (getSuserId() == null ? 0 : this.getSuserId().hashCode());
		result = 37 * result + (getContributorsIdx() == null ? 0 : this.getContributorsIdx().hashCode());
		return result;
	}

}
