package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaxonomyDefinitionAuthor generated by hbm2java
 */
@Entity
@Table(name = "taxonomy_definition_author", schema = "public")
public class TaxonomyDefinitionAuthor implements java.io.Serializable {

	private TaxonomyDefinitionAuthorId id;
	private TaxonomyDefinition taxonomyDefinition;

	public TaxonomyDefinitionAuthor() {
	}

	public TaxonomyDefinitionAuthor(TaxonomyDefinitionAuthorId id) {
		this.id = id;
	}

	public TaxonomyDefinitionAuthor(TaxonomyDefinitionAuthorId id, TaxonomyDefinition taxonomyDefinition) {
		this.id = id;
		this.taxonomyDefinition = taxonomyDefinition;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxonomyDefinitionId", column = @Column(name = "taxonomy_definition_id")),
			@AttributeOverride(name = "authorString", column = @Column(name = "author_string")) })
	public TaxonomyDefinitionAuthorId getId() {
		return this.id;
	}

	public void setId(TaxonomyDefinitionAuthorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxonomy_definition_id", insertable = false, updatable = false)
	public TaxonomyDefinition getTaxonomyDefinition() {
		return this.taxonomyDefinition;
	}

	public void setTaxonomyDefinition(TaxonomyDefinition taxonomyDefinition) {
		this.taxonomyDefinition = taxonomyDefinition;
	}

}
