package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaxonomyDefinitionYear generated by hbm2java
 */
@Entity
@Table(name = "taxonomy_definition_year", schema = "public")
public class TaxonomyDefinitionYear implements java.io.Serializable {

	private TaxonomyDefinitionYearId id;
	private TaxonomyDefinition taxonomyDefinition;

	public TaxonomyDefinitionYear() {
	}

	public TaxonomyDefinitionYear(TaxonomyDefinitionYearId id) {
		this.id = id;
	}

	public TaxonomyDefinitionYear(TaxonomyDefinitionYearId id, TaxonomyDefinition taxonomyDefinition) {
		this.id = id;
		this.taxonomyDefinition = taxonomyDefinition;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxonomyDefinitionId", column = @Column(name = "taxonomy_definition_id")),
			@AttributeOverride(name = "yearString", column = @Column(name = "year_string")) })
	public TaxonomyDefinitionYearId getId() {
		return this.id;
	}

	public void setId(TaxonomyDefinitionYearId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxonomy_definition_id", insertable = false, updatable = false)
	public TaxonomyDefinition getTaxonomyDefinition() {
		return this.taxonomyDefinition;
	}

	public void setTaxonomyDefinition(TaxonomyDefinition taxonomyDefinition) {
		this.taxonomyDefinition = taxonomyDefinition;
	}

}
