package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TemporalCoverage generated by hbm2java
 */
@Entity
@Table(name = "temporal_coverage", schema = "public")
public class TemporalCoverage implements java.io.Serializable {

	private long id;
	private long version;
	private Date fromDate;
	private Date singleDateTime;
	private Date toDate;

	public TemporalCoverage() {
	}

	public TemporalCoverage(long id, Date singleDateTime) {
		this.id = id;
		this.singleDateTime = singleDateTime;
	}

	public TemporalCoverage(long id, Date fromDate, Date singleDateTime, Date toDate) {
		this.id = id;
		this.fromDate = fromDate;
		this.singleDateTime = singleDateTime;
		this.toDate = toDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "from_date", length = 29)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "single_date_time", nullable = false, length = 29)
	public Date getSingleDateTime() {
		return this.singleDateTime;
	}

	public void setSingleDateTime(Date singleDateTime) {
		this.singleDateTime = singleDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "to_date", length = 29)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
