package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Topology generated by hbm2java
 */
@Entity
@Table(name = "topology", schema = "topology", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Topology implements java.io.Serializable {

	private int id;
	private String name;
	private int srid;
	private double precision;
	private boolean hasz;
	private Set layers = new HashSet(0);

	public Topology() {
	}

	public Topology(int id, String name, int srid, double precision, boolean hasz) {
		this.id = id;
		this.name = name;
		this.srid = srid;
		this.precision = precision;
		this.hasz = hasz;
	}

	public Topology(int id, String name, int srid, double precision, boolean hasz, Set layers) {
		this.id = id;
		this.name = name;
		this.srid = srid;
		this.precision = precision;
		this.hasz = hasz;
		this.layers = layers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "srid", nullable = false)
	public int getSrid() {
		return this.srid;
	}

	public void setSrid(int srid) {
		this.srid = srid;
	}

	@Column(name = "precision", nullable = false, precision = 17, scale = 17)
	public double getPrecision() {
		return this.precision;
	}

	public void setPrecision(double precision) {
		this.precision = precision;
	}

	@Column(name = "hasz", nullable = false)
	public boolean isHasz() {
		return this.hasz;
	}

	public void setHasz(boolean hasz) {
		this.hasz = hasz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topology")
	public Set getLayers() {
		return this.layers;
	}

	public void setLayers(Set layers) {
		this.layers = layers;
	}

}
