package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TraitTaxonomyDefinition generated by hbm2java
 */
@Entity
@Table(name = "trait_taxonomy_definition", schema = "public")
public class TraitTaxonomyDefinition implements java.io.Serializable {

	private TraitTaxonomyDefinitionId id;
	private Trait trait;
	private TaxonomyDefinition taxonomyDefinition;

	public TraitTaxonomyDefinition() {
	}

	public TraitTaxonomyDefinition(TraitTaxonomyDefinitionId id) {
		this.id = id;
	}

	public TraitTaxonomyDefinition(TraitTaxonomyDefinitionId id, Trait trait, TaxonomyDefinition taxonomyDefinition) {
		this.id = id;
		this.trait = trait;
		this.taxonomyDefinition = taxonomyDefinition;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "traitTaxonId", column = @Column(name = "trait_taxon_id")),
			@AttributeOverride(name = "taxonomyDefinitionId", column = @Column(name = "taxonomy_definition_id")) })
	public TraitTaxonomyDefinitionId getId() {
		return this.id;
	}

	public void setId(TraitTaxonomyDefinitionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trait_taxon_id", insertable = false, updatable = false)
	public Trait getTrait() {
		return this.trait;
	}

	public void setTrait(Trait trait) {
		this.trait = trait;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxonomy_definition_id", insertable = false, updatable = false)
	public TaxonomyDefinition getTaxonomyDefinition() {
		return this.taxonomyDefinition;
	}

	public void setTaxonomyDefinition(TaxonomyDefinition taxonomyDefinition) {
		this.taxonomyDefinition = taxonomyDefinition;
	}

}
