package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserGroupHabitatId generated by hbm2java
 */
@Embeddable
public class UserGroupHabitatId implements java.io.Serializable {

	private Long userGroupHabitatsId;
	private Long habitatId;

	public UserGroupHabitatId() {
	}

	public UserGroupHabitatId(Long userGroupHabitatsId, Long habitatId) {
		this.userGroupHabitatsId = userGroupHabitatsId;
		this.habitatId = habitatId;
	}

	@Column(name = "user_group_habitats_id")
	public Long getUserGroupHabitatsId() {
		return this.userGroupHabitatsId;
	}

	public void setUserGroupHabitatsId(Long userGroupHabitatsId) {
		this.userGroupHabitatsId = userGroupHabitatsId;
	}

	@Column(name = "habitat_id")
	public Long getHabitatId() {
		return this.habitatId;
	}

	public void setHabitatId(Long habitatId) {
		this.habitatId = habitatId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGroupHabitatId))
			return false;
		UserGroupHabitatId castOther = (UserGroupHabitatId) other;

		return ((this.getUserGroupHabitatsId() == castOther.getUserGroupHabitatsId())
				|| (this.getUserGroupHabitatsId() != null && castOther.getUserGroupHabitatsId() != null
						&& this.getUserGroupHabitatsId().equals(castOther.getUserGroupHabitatsId())))
				&& ((this.getHabitatId() == castOther.getHabitatId()) || (this.getHabitatId() != null
						&& castOther.getHabitatId() != null && this.getHabitatId().equals(castOther.getHabitatId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserGroupHabitatsId() == null ? 0 : this.getUserGroupHabitatsId().hashCode());
		result = 37 * result + (getHabitatId() == null ? 0 : this.getHabitatId().hashCode());
		return result;
	}

}
