package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserGroupHabitat generated by hbm2java
 */
@Entity
@Table(name = "user_group_habitat", schema = "public")
public class UserGroupHabitat implements java.io.Serializable {

	private UserGroupHabitatId id;
	private Habitat habitat;
	private UserGroup userGroup;

	public UserGroupHabitat() {
	}

	public UserGroupHabitat(UserGroupHabitatId id) {
		this.id = id;
	}

	public UserGroupHabitat(UserGroupHabitatId id, Habitat habitat, UserGroup userGroup) {
		this.id = id;
		this.habitat = habitat;
		this.userGroup = userGroup;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userGroupHabitatsId", column = @Column(name = "user_group_habitats_id")),
			@AttributeOverride(name = "habitatId", column = @Column(name = "habitat_id")) })
	public UserGroupHabitatId getId() {
		return this.id;
	}

	public void setId(UserGroupHabitatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "habitat_id", insertable = false, updatable = false)
	public Habitat getHabitat() {
		return this.habitat;
	}

	public void setHabitat(Habitat habitat) {
		this.habitat = habitat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_group_habitats_id", insertable = false, updatable = false)
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

}
