package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserGroupMemberRole generated by hbm2java
 */
@Entity
@Table(name = "user_group_member_role", schema = "public")
public class UserGroupMemberRole implements java.io.Serializable {

	private UserGroupMemberRoleId id;
	private Suser suser;
	private UserGroup userGroup;
	private Role role;

	public UserGroupMemberRole() {
	}

	public UserGroupMemberRole(UserGroupMemberRoleId id, Suser suser, UserGroup userGroup, Role role) {
		this.id = id;
		this.suser = suser;
		this.userGroup = userGroup;
		this.role = role;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userGroupId", column = @Column(name = "user_group_id", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "SUserId", column = @Column(name = "s_user_id", nullable = false)) })
	public UserGroupMemberRoleId getId() {
		return this.id;
	}

	public void setId(UserGroupMemberRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "s_user_id", nullable = false, insertable = false, updatable = false)
	public Suser getSuser() {
		return this.suser;
	}

	public void setSuser(Suser suser) {
		this.suser = suser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_group_id", nullable = false, insertable = false, updatable = false)
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
