package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserGroupMemberRoleId generated by hbm2java
 */
@Embeddable
public class UserGroupMemberRoleId implements java.io.Serializable {

	private long userGroupId;
	private long roleId;
	private long SUserId;

	public UserGroupMemberRoleId() {
	}

	public UserGroupMemberRoleId(long userGroupId, long roleId, long SUserId) {
		this.userGroupId = userGroupId;
		this.roleId = roleId;
		this.SUserId = SUserId;
	}

	@Column(name = "user_group_id", nullable = false)
	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	@Column(name = "role_id", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "s_user_id", nullable = false)
	public long getSUserId() {
		return this.SUserId;
	}

	public void setSUserId(long SUserId) {
		this.SUserId = SUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGroupMemberRoleId))
			return false;
		UserGroupMemberRoleId castOther = (UserGroupMemberRoleId) other;

		return (this.getUserGroupId() == castOther.getUserGroupId()) && (this.getRoleId() == castOther.getRoleId())
				&& (this.getSUserId() == castOther.getSUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserGroupId();
		result = 37 * result + (int) this.getRoleId();
		result = 37 * result + (int) this.getSUserId();
		return result;
	}

}
