package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserGroupNewsletter generated by hbm2java
 */
@Entity
@Table(name = "user_group_newsletter", schema = "public")
public class UserGroupNewsletter implements java.io.Serializable {

	private UserGroupNewsletterId id;
	private Newsletter newsletter;
	private UserGroup userGroup;

	public UserGroupNewsletter() {
	}

	public UserGroupNewsletter(UserGroupNewsletterId id) {
		this.id = id;
	}

	public UserGroupNewsletter(UserGroupNewsletterId id, Newsletter newsletter, UserGroup userGroup) {
		this.id = id;
		this.newsletter = newsletter;
		this.userGroup = userGroup;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userGroupNewslettersId", column = @Column(name = "user_group_newsletters_id")),
			@AttributeOverride(name = "newsletterId", column = @Column(name = "newsletter_id")) })
	public UserGroupNewsletterId getId() {
		return this.id;
	}

	public void setId(UserGroupNewsletterId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "newsletter_id", insertable = false, updatable = false)
	public Newsletter getNewsletter() {
		return this.newsletter;
	}

	public void setNewsletter(Newsletter newsletter) {
		this.newsletter = newsletter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_group_newsletters_id", insertable = false, updatable = false)
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

}
