package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserGroupSpeciesGroup generated by hbm2java
 */
@Entity
@Table(name = "user_group_species_group", schema = "public")
public class UserGroupSpeciesGroup implements java.io.Serializable {

	private UserGroupSpeciesGroupId id;
	private UserGroup userGroup;
	private SpeciesGroup speciesGroup;

	public UserGroupSpeciesGroup() {
	}

	public UserGroupSpeciesGroup(UserGroupSpeciesGroupId id) {
		this.id = id;
	}

	public UserGroupSpeciesGroup(UserGroupSpeciesGroupId id, UserGroup userGroup, SpeciesGroup speciesGroup) {
		this.id = id;
		this.userGroup = userGroup;
		this.speciesGroup = speciesGroup;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userGroupSpeciesGroupsId", column = @Column(name = "user_group_species_groups_id")),
			@AttributeOverride(name = "speciesGroupId", column = @Column(name = "species_group_id")) })
	public UserGroupSpeciesGroupId getId() {
		return this.id;
	}

	public void setId(UserGroupSpeciesGroupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_group_species_groups_id", insertable = false, updatable = false)
	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "species_group_id", insertable = false, updatable = false)
	public SpeciesGroup getSpeciesGroup() {
		return this.speciesGroup;
	}

	public void setSpeciesGroup(SpeciesGroup speciesGroup) {
		this.speciesGroup = speciesGroup;
	}

}
