package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserTokenParamsId generated by hbm2java
 */
@Embeddable
public class UserTokenParamsId implements java.io.Serializable {

	private Long params;
	private String paramsIdx;
	private String paramsElt;

	public UserTokenParamsId() {
	}

	public UserTokenParamsId(String paramsElt) {
		this.paramsElt = paramsElt;
	}

	public UserTokenParamsId(Long params, String paramsIdx, String paramsElt) {
		this.params = params;
		this.paramsIdx = paramsIdx;
		this.paramsElt = paramsElt;
	}

	@Column(name = "params")
	public Long getParams() {
		return this.params;
	}

	public void setParams(Long params) {
		this.params = params;
	}

	@Column(name = "params_idx")
	public String getParamsIdx() {
		return this.paramsIdx;
	}

	public void setParamsIdx(String paramsIdx) {
		this.paramsIdx = paramsIdx;
	}

	@Column(name = "params_elt", nullable = false)
	public String getParamsElt() {
		return this.paramsElt;
	}

	public void setParamsElt(String paramsElt) {
		this.paramsElt = paramsElt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserTokenParamsId))
			return false;
		UserTokenParamsId castOther = (UserTokenParamsId) other;

		return ((this.getParams() == castOther.getParams()) || (this.getParams() != null
				&& castOther.getParams() != null && this.getParams().equals(castOther.getParams())))
				&& ((this.getParamsIdx() == castOther.getParamsIdx()) || (this.getParamsIdx() != null
						&& castOther.getParamsIdx() != null && this.getParamsIdx().equals(castOther.getParamsIdx())))
				&& ((this.getParamsElt() == castOther.getParamsElt()) || (this.getParamsElt() != null
						&& castOther.getParamsElt() != null && this.getParamsElt().equals(castOther.getParamsElt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getParams() == null ? 0 : this.getParams().hashCode());
		result = 37 * result + (getParamsIdx() == null ? 0 : this.getParamsIdx().hashCode());
		result = 37 * result + (getParamsElt() == null ? 0 : this.getParamsElt().hashCode());
		return result;
	}

}
