package biodiv;
// Generated 31 Jul, 2017 7:18:53 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserGroupObservationId generated by hbm2java
 */
@Embeddable
public class UserGroupObservationId implements java.io.Serializable {

	private Long userGroupObservationsId;
	private Long observationId;

	public UserGroupObservationId() {
	}

	public UserGroupObservationId(Long userGroupObservationsId, Long observationId) {
		this.userGroupObservationsId = userGroupObservationsId;
		this.observationId = observationId;
	}

	@Column(name = "user_group_observations_id")
	public Long getUserGroupObservationsId() {
		return this.userGroupObservationsId;
	}

	public void setUserGroupObservationsId(Long userGroupObservationsId) {
		this.userGroupObservationsId = userGroupObservationsId;
	}

	@Column(name = "observation_id")
	public Long getObservationId() {
		return this.observationId;
	}

	public void setObservationId(Long observationId) {
		this.observationId = observationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGroupObservationId))
			return false;
		UserGroupObservationId castOther = (UserGroupObservationId) other;

		return ((this.getUserGroupObservationsId() == castOther.getUserGroupObservationsId())
				|| (this.getUserGroupObservationsId() != null && castOther.getUserGroupObservationsId() != null
						&& this.getUserGroupObservationsId().equals(castOther.getUserGroupObservationsId())))
				&& ((this.getObservationId() == castOther.getObservationId())
						|| (this.getObservationId() != null && castOther.getObservationId() != null
								&& this.getObservationId().equals(castOther.getObservationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserGroupObservationsId() == null ? 0 : this.getUserGroupObservationsId().hashCode());
		result = 37 * result + (getObservationId() == null ? 0 : this.getObservationId().hashCode());
		return result;
	}

}
